export const courses = [
  {
    id: "course_001",
    title: "Introduction to Golang",
    subtitle: "Learn the fundamentals of Go by building real projects",
    description:
      "A beginner-friendly course teaching core Go concepts including syntax, concurrency, and building simple APIs.",
    instructor: {
      name: "John Doe",
      avatar: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    },
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    duration: "6h 30m",
    difficulty: "Beginner",
    categories: ["Programming", "Backend Development", "Golang"],
    level: 1,
    studentsEnrolled: 1275,
    rating: 4.8,
    tags: ["go", "backend", "api", "concurrency"],
    updatedAt: "2025-10-10T12:00:00Z",
    isFree: false,
    price: { amount: 49.99, currency: "USD" },
    progress: 65,
    chapters: [
      {
        id: "chapter_001_001",
        title: "Getting Started with Go",
        description: "Introduction to Go syntax and basic concepts",
        order: 1,
        lessons: [
          {
            completed: true,
            id: "lesson_001_001_001",
            title: "Installing Go and Setting Up Your Environment",
            description:
              "Learn how to install Go and configure your development environment",
            duration: "12m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_001_001_001_001",
                type: "video",
                title: "Installation Guide",
                url: "https://www.youtube.com/embed/YS4e4q9oBaU",
                duration: "8m",
              },
              {
                id: "material_001_001_001_002",
                type: "video",
                title: "Setting Up VS Code for Go",
                url: "https://www.youtube.com/embed/1MXIGYrMk80",
                duration: "12m",
              },
              {
                id: "material_001_001_001_003",
                type: "document",
                title: "Go Language Documentation",
                url: "https://pdfobject.com/pdf/sample.pdf",
                duration: "15m",
              },
              {
                id: "material_001_001_001_004",
                type: "document",
                title: "Setup Checklist",
                url: "https://go.dev/doc/install",
                duration: "5m",
              },
              {
                id: "material_001_001_001_005",
                type: "code",
                title: "Quick Start Code Examples",
                url: "https://go.dev/play/",
              },
              {
                id: "material_001_001_001_006",
                type: "exercise",
                title: "Verify Your Installation",
                url: "https://go.dev/tour/welcome/1",
              },
              {
                id: "material_001_001_001_007",
                type: "link",
                title: "Official Go Website",
                url: "https://go.dev",
              },
              {
                id: "material_001_001_001_008",
                type: "document",
                title: "Troubleshooting Common Issues",
                url: "https://go.dev/doc/install/source",
                duration: "8m",
              },
              {
                id: "material_001_001_001_009",
                type: "quiz",
                title: "Environment Setup Quiz",
                url: "https://go.dev/tour/welcome/1",
                questionsCount: 5,
              },
            ],
          },
          {
            id: "lesson_001_001_002",
            title: "Your First Go Program",
            description: "Write and run your first Hello World program in Go",
            duration: "15m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_001_002_001",
                type: "video",
                title: "Hello World Tutorial",
                url: "https://www.youtube.com/embed/446E-r0rXHI",
                duration: "10m",
              },
              {
                id: "material_001_001_002_002",
                type: "code",
                title: "Starter Code",
                url: "https://go.dev/play/p/fvVu6MpBCMi",
              },
              {
                id: "material_001_001_002_003",
                type: "exercise",
                title: "Practice Exercise: Variables",
                url: "https://exercism.org/tracks/go/exercises/hello-world",
              },
            ],
          },
          {
            id: "lesson_001_001_003",
            title: "Understanding Go Workspace and Modules",
            description: "Learn about Go modules, workspace structure, and dependency management",
            duration: "18m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_001_003_001",
                type: "video",
                title: "Go Modules Explained",
                url: "https://www.youtube.com/embed/Z1VhG7cf83M",
                duration: "12m",
              },
              {
                id: "material_001_001_003_002",
                type: "document",
                title: "Go Modules Reference",
                url: "https://pdfobject.com/pdf/sample.pdf",
                duration: "8m",
              },
              {
                id: "material_001_001_003_003",
                type: "code",
                title: "Module Examples",
                url: "https://go.dev/play/",
              },
            ],
          },
          {
            id: "lesson_001_001_004",
            title: "Go Tools and CLI Commands",
            description: "Master essential Go command-line tools",
            duration: "14m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_001_004_001",
                type: "video",
                title: "Go CLI Tools Overview",
                url: "https://www.youtube.com/embed/XCsL89YtqCs",
                duration: "10m",
              },
              {
                id: "material_001_001_004_002",
                type: "document",
                title: "Command Reference Guide",
                url: "https://go.dev/doc/",
                duration: "6m",
              },
            ],
          },
          {
            id: "lesson_001_001_005",
            title: "Basic Go Syntax and Structure",
            description: "Understand the fundamental syntax rules and program structure in Go",
            duration: "20m",
            order: 5,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_001_005_001",
                type: "video",
                title: "Go Syntax Basics",
                url: "https://www.youtube.com/embed/YS4e4q9oBaU",
                duration: "14m",
              },
              {
                id: "material_001_001_005_002",
                type: "code",
                title: "Syntax Examples",
                url: "https://gobyexample.com/",
              },
              {
                id: "material_001_001_005_003",
                type: "exercise",
                title: "Syntax Practice",
                url: "https://go.dev/tour/basics/1",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_002",
        title: "Go Fundamentals",
        description: "Deep dive into Go's core features",
        order: 2,
        lessons: [
          {
            id: "lesson_001_002_001",
            title: "Variables and Data Types",
            description: "Understanding Go's type system",
            duration: "20m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_001_001",
                type: "video",
                title: "Data Types Explained",
                url: "https://www.youtube.com/watch?v=pM0-CMysa_M",
                duration: "15m",
              },
              {
                id: "material_001_002_001_002",
                type: "document",
                title: "Type System Reference",
                url: "https://go.dev/ref/spec#Types",
              },
            ],
          },
          {
            id: "lesson_001_002_002",
            title: "Control Structures",
            description: "Learn if-else, loops, and switch statements in Go",
            duration: "25m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_002_001",
                type: "video",
                title: "Control Flow in Go",
                url: "https://www.youtube.com/watch?v=X2WS5pKnk3M",
                duration: "18m",
              },
              {
                id: "material_001_002_002_002",
                type: "exercise",
                title: "Loop Exercises",
                url: "https://go.dev/tour/flowcontrol/1",
              },
            ],
          },
          {
            id: "lesson_001_002_003",
            title: "Functions and Methods",
            description: "Master functions, methods, and receivers",
            duration: "30m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_003_001",
                type: "video",
                title: "Functions Deep Dive",
                url: "https://www.youtube.com/watch?v=rr7tM5_V7QQ",
                duration: "22m",
              },
              {
                id: "material_001_002_003_002",
                type: "code",
                title: "Method Examples",
                url: "https://gobyexample.com/methods",
              },
            ],
          },
          {
            id: "lesson_001_002_004",
            title: "Structs and Pointers",
            description: "Working with structs and pointer mechanics",
            duration: "27m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_004_001",
                type: "video",
                title: "Structs Explained",
                url: "https://www.youtube.com/watch?v=v9FHhHMH430",
                duration: "20m",
              },
              {
                id: "material_001_002_004_002",
                type: "exercise",
                title: "Struct Practice",
                url: "https://gobyexample.com/structs",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_003",
        title: "Advanced Go Concepts",
        description: "Master concurrency, interfaces, and error handling",
        order: 3,
        lessons: [
          {
            id: "lesson_001_003_001",
            title: "Goroutines and Channels",
            description: "Understanding Go's concurrency model",
            duration: "35m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_003_001_001",
                type: "video",
                title: "Concurrency Fundamentals",
                url: "https://www.youtube.com/watch?v=LvgVSSpwND8",
                duration: "28m",
              },
              {
                id: "material_001_003_001_002",
                type: "exercise",
                title: "Goroutine Practice",
                url: "https://gobyexample.com/goroutines",
              },
            ],
          },
          {
            id: "lesson_001_003_002",
            title: "Interfaces and Type Assertions",
            description: "Polymorphism in Go",
            duration: "28m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_003_002_001",
                type: "video",
                title: "Understanding Interfaces",
                url: "https://www.youtube.com/watch?v=qJKQZKGZgf0",
                duration: "20m",
              },
              {
                id: "material_001_003_002_002",
                type: "document",
                title: "Interface Patterns",
                url: "https://go.dev/tour/methods/9",
              },
            ],
          },
          {
            id: "lesson_001_003_003",
            title: "Error Handling Best Practices",
            description: "Proper error handling in Go applications",
            duration: "22m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_003_003_001",
                type: "video",
                title: "Error Handling Patterns",
                url: "https://www.youtube.com/watch?v=6YM5WkF9A0c",
                duration: "18m",
              },
              {
                id: "material_001_003_003_002",
                type: "quiz",
                title: "Error Handling Quiz",
                url: "https://go.dev/blog/error-handling-and-go",
                questionsCount: 8,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_004",
        title: "Building REST APIs",
        description: "Create production-ready APIs with Go",
        order: 4,
        lessons: [
          {
            id: "lesson_001_004_001",
            title: "HTTP Server Basics",
            description: "Building your first HTTP server",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_004_001_001",
                type: "video",
                title: "HTTP Server Setup",
                url: "https://www.youtube.com/watch?v=oy1mPiW_d2E",
                duration: "25m",
              },
              {
                id: "material_001_004_001_002",
                type: "code",
                title: "Server Starter Template",
                url: "https://gobyexample.com/http-servers",
              },
            ],
          },
          {
            id: "lesson_001_004_002",
            title: "Routing and Middleware",
            description: "Implement routing patterns and middleware",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_004_002_001",
                type: "video",
                title: "Routing with Gorilla Mux",
                url: "https://www.youtube.com/watch?v=vXtf9nJygXs",
                duration: "26m",
              },
              {
                id: "material_001_004_002_002",
                type: "exercise",
                title: "Build a REST API",
                url: "https://github.com/gorilla/mux#examples",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_005",
        title: "Testing and Best Practices",
        description: "Write tests and follow Go conventions",
        order: 5,
        lessons: [
          {
            id: "lesson_001_005_001",
            title: "Writing Unit Tests",
            description: "Test your Go code effectively",
            duration: "33m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_005_001_001",
                type: "video",
                title: "Testing in Go",
                url: "https://www.youtube.com/watch?v=prjjXD2xYKE",
                duration: "26m",
              },
              {
                id: "material_001_005_001_002",
                type: "code",
                title: "Test Examples",
                url: "https://gobyexample.com/testing",
              },
            ],
          },
          {
            id: "lesson_001_005_002",
            title: "Final Project",
            description: "Build a complete REST API with database",
            duration: "55m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_005_002_001",
                type: "video",
                title: "Project Walkthrough",
                url: "https://www.youtube.com/watch?v=XCsL89YtqCs",
                duration: "48m",
              },
              {
                id: "material_001_005_002_002",
                type: "exercise",
                title: "Complete API Project",
                url: "https://github.com/mactsouk/rest-api",
              },
              {
                id: "material_001_005_002_003",
                type: "quiz",
                title: "Final Assessment",
                url: "https://go.dev/tour/list",
                questionsCount: 20,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_002",
    title: "React for Beginners",
    subtitle: "Build dynamic frontends with modern React and Hooks",
    description:
      "Learn how to build scalable frontends using React, Hooks, Context API, and reusable components.",
    instructor: {
      name: "Emily Carter",
      avatar: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39",
    },
    thumbnail: "https://images.unsplash.com/photo-1587620962725-abab7fe55159",
    duration: "4h 45m",
    difficulty: "Beginner",
    categories: ["Frontend", "JavaScript", "React"],
    level: 1,
    studentsEnrolled: 3400,
    rating: 4.7,
    tags: ["react", "frontend", "hooks"],
    updatedAt: "2025-09-18T12:00:00Z",
    isFree: true,
    price: null,
    progress: 30,
    chapters: [
      {
        id: "chapter_002_001",
        title: "React Basics",
        description: "Introduction to React components and JSX",
        order: 1,
        lessons: [
          {
            id: "lesson_002_001_001",
            title: "What is React?",
            description: "Understanding React and its ecosystem",
            duration: "18m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_002_001_001_001",
                type: "video",
                title: "React Introduction",
                url: "https://www.youtube.com/watch?v=Tn6-PIqc4UM",
                duration: "12m",
              },
              {
                id: "material_002_001_001_002",
                type: "document",
                title: "React Overview",
                url: "https://react.dev/learn",
              },
              {
                id: "material_002_001_001_003",
                type: "link",
                title: "Official React Docs",
                url: "https://react.dev",
              },
            ],
          },
          {
            id: "lesson_002_001_002",
            title: "JSX Fundamentals",
            description: "Learn JSX syntax and best practices",
            duration: "22m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_002_001_002_001",
                type: "video",
                title: "JSX Deep Dive",
                url: "https://www.youtube.com/watch?v=kVeOpcw4GWY",
                duration: "16m",
              },
              {
                id: "material_002_001_002_002",
                type: "code",
                title: "JSX Examples",
                url: "https://react.dev/learn/writing-markup-with-jsx",
              },
            ],
          },
          {
            id: "lesson_002_001_003",
            title: "Components and Props",
            description: "Build reusable components with props",
            duration: "26m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_001_003_001",
                type: "video",
                title: "Component Composition",
                url: "https://www.youtube.com/watch?v=5yPdXnSyuRM",
                duration: "20m",
              },
              {
                id: "material_002_001_003_002",
                type: "exercise",
                title: "Build Components",
                url: "https://react.dev/learn/passing-props-to-a-component",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_002",
        title: "State and Lifecycle",
        description: "Managing component state and lifecycle methods",
        order: 2,
        lessons: [
          {
            id: "lesson_002_002_001",
            title: "useState Hook",
            description: "Managing state with React Hooks",
            duration: "24m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_002_001_001",
                type: "video",
                title: "useState Explained",
                url: "https://www.youtube.com/watch?v=O6P86uwfdR0",
                duration: "18m",
              },
              {
                id: "material_002_002_001_002",
                type: "code",
                title: "State Examples",
                url: "https://react.dev/reference/react/useState",
              },
            ],
          },
          {
            id: "lesson_002_002_002",
            title: "useEffect Hook",
            description: "Side effects and lifecycle in functional components",
            duration: "28m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_002_002_001",
                type: "video",
                title: "useEffect Mastery",
                url: "https://www.youtube.com/watch?v=0ZJgIjIuY7U",
                duration: "22m",
              },
              {
                id: "material_002_002_002_002",
                type: "exercise",
                title: "Effect Practice",
                url: "https://react.dev/reference/react/useEffect",
              },
              {
                id: "material_002_002_002_003",
                type: "quiz",
                title: "Hooks Quiz",
                url: "https://react.dev/learn/managing-state",
                questionsCount: 10,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_003",
        title: "Advanced Hooks",
        description: "Master useContext, useReducer, and custom hooks",
        order: 3,
        lessons: [
          {
            id: "lesson_002_003_001",
            title: "Context API and useContext",
            description: "Global state management with Context",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_003_001_001",
                type: "video",
                title: "Context API Guide",
                url: "https://www.youtube.com/watch?v=5LrDIWkK_Bc",
                duration: "24m",
              },
              {
                id: "material_002_003_001_002",
                type: "document",
                title: "Context Patterns",
                url: "https://react.dev/learn/passing-data-deeply-with-context",
              },
            ],
          },
          {
            id: "lesson_002_003_002",
            title: "useReducer for Complex State",
            description: "Redux-like state management with useReducer",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_003_002_001",
                type: "video",
                title: "useReducer Tutorial",
                url: "https://www.youtube.com/watch?v=kK_Wqx3RnHk",
                duration: "26m",
              },
              {
                id: "material_002_003_002_002",
                type: "code",
                title: "Reducer Examples",
                url: "https://react.dev/reference/react/useReducer",
              },
            ],
          },
          {
            id: "lesson_002_003_003",
            title: "Building Custom Hooks",
            description: "Create reusable custom hooks",
            duration: "28m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_003_003_001",
                type: "video",
                title: "Custom Hooks",
                url: "https://www.youtube.com/watch?v=6ThXsUwLWvc",
                duration: "22m",
              },
              {
                id: "material_002_003_003_002",
                type: "exercise",
                title: "Build Your Own Hook",
                url: "https://react.dev/learn/reusing-logic-with-custom-hooks",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_004",
        title: "Building Real Applications",
        description: "Put it all together in a complete project",
        order: 4,
        lessons: [
          {
            id: "lesson_002_004_001",
            title: "Project Setup and Architecture",
            description: "Structure a production React app",
            duration: "25m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_001_001",
                type: "video",
                title: "App Architecture",
                url: "https://www.youtube.com/watch?v=NqzdVN2tyvQ",
                duration: "20m",
              },
              {
                id: "material_002_004_001_002",
                type: "code",
                title: "Starter Template",
                url: "https://vitejs.dev/guide/#scaffolding-your-first-vite-project",
              },
            ],
          },
          {
            id: "lesson_002_004_002",
            title: "API Integration",
            description: "Fetch and display data from APIs",
            duration: "35m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_002_001",
                type: "video",
                title: "Data Fetching",
                url: "https://www.youtube.com/watch?v=cuHDQhDhvPE",
                duration: "28m",
              },
              {
                id: "material_002_004_002_002",
                type: "exercise",
                title: "Build API Client",
                url: "https://react.dev/learn/synchronizing-with-effects#fetching-data",
              },
            ],
          },
          {
            id: "lesson_002_004_003",
            title: "Routing with React Router",
            description: "Navigate between pages",
            duration: "30m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_003_001",
                type: "video",
                title: "React Router Guide",
                url: "https://www.youtube.com/watch?v=Ul3y1LXxzdU",
                duration: "24m",
              },
              {
                id: "material_002_004_003_002",
                type: "code",
                title: "Routing Examples",
                url: "https://reactrouter.com/en/main/start/tutorial",
              },
            ],
          },
          {
            id: "lesson_002_004_004",
            title: "Final Project",
            description: "Build a complete Todo application",
            duration: "45m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_004_001",
                type: "video",
                title: "Project Walkthrough",
                url: "https://www.youtube.com/watch?v=hQAHSlTtcmY",
                duration: "40m",
              },
              {
                id: "material_002_004_004_002",
                type: "exercise",
                title: "Complete Project",
                url: "https://github.com/tastejs/todomvc",
              },
              {
                id: "material_002_004_004_003",
                type: "quiz",
                title: "Final Assessment",
                url: "https://react.dev/learn/tutorial-tic-tac-toe",
                questionsCount: 15,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_005",
        title: "Performance and Optimization",
        description: "Make your React apps blazing fast",
        order: 5,
        lessons: [
          {
            id: "lesson_002_005_001",
            title: "React.memo and useMemo",
            description: "Optimize rendering performance",
            duration: "26m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_005_001_001",
                type: "video",
                title: "Performance Optimization",
                url: "https://www.youtube.com/watch?v=uojLJFt9SzY",
                duration: "20m",
              },
              {
                id: "material_002_005_001_002",
                type: "exercise",
                title: "Optimization Practice",
                url: "https://react.dev/reference/react/memo",
              },
            ],
          },
          {
            id: "lesson_002_005_002",
            title: "Code Splitting and Lazy Loading",
            description: "Reduce bundle size and improve load times",
            duration: "22m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_005_002_001",
                type: "video",
                title: "Code Splitting Guide",
                url: "https://www.youtube.com/watch?v=JU6sl_yyZqs",
                duration: "18m",
              },
              {
                id: "material_002_005_002_002",
                type: "quiz",
                title: "Performance Quiz",
                url: "https://react.dev/reference/react/lazy",
                questionsCount: 8,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_003",
    title: "Advanced Node.js APIs",
    subtitle: "Master REST API design, authentication, testing, and scaling",
    description:
      "A deep dive into production-ready Node.js backend architecture using Express, Prisma, and automated testing.",
    instructor: {
      name: "Michael Thompson",
      avatar: "https://images.unsplash.com/photo-1527980965255-d3b416303d12",
    },
    thumbnail: "https://images.unsplash.com/photo-1518779578993-ec3579fee39f",
    duration: "8h 10m",
    difficulty: "Advanced",
    categories: ["Backend", "Node.js", "APIs"],
    level: 3,
    studentsEnrolled: 980,
    rating: 4.9,
    tags: ["node", "api", "express", "prisma"],
    updatedAt: "2025-08-21T12:00:00Z",
    isFree: false,
    price: { amount: 69.0, currency: "USD" },
    progress: 15,
    chapters: [
      {
        id: "chapter_003_001",
        title: "API Architecture",
        description: "Designing scalable REST APIs",
        order: 1,
        lessons: [
          {
            id: "lesson_003_001_001",
            title: "RESTful Design Principles",
            description: "Best practices for API design",
            duration: "25m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_001_001_001",
                type: "video",
                title: "REST API Design",
                url: "https://www.youtube.com/watch?v=qwfE7fSVaZM",
                duration: "20m",
              },
              {
                id: "material_003_001_001_002",
                type: "document",
                title: "API Design Guide",
                url: "https://restfulapi.net/",
              },
            ],
          },
          {
            id: "lesson_003_001_002",
            title: "Express.js Advanced Patterns",
            description: "Mastering Express middleware and routing",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_001_002_001",
                type: "video",
                title: "Express Deep Dive",
                url: "https://www.youtube.com/watch?v=Lr9WUkeYSA8",
                duration: "28m",
              },
              {
                id: "material_003_001_002_002",
                type: "code",
                title: "Advanced Patterns",
                url: "https://expressjs.com/en/guide/routing.html",
              },
            ],
          },
          {
            id: "lesson_003_001_003",
            title: "Error Handling and Validation",
            description: "Production-grade error handling strategies",
            duration: "28m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_001_003_001",
                type: "video",
                title: "Error Handling",
                url: "https://www.youtube.com/watch?v=w2o-PL8z-K4",
                duration: "22m",
              },
              {
                id: "material_003_001_003_002",
                type: "exercise",
                title: "Validation Practice",
                url: "https://express-validator.github.io/docs/",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_003_002",
        title: "Authentication and Security",
        description: "Implement JWT, OAuth, and security best practices",
        order: 2,
        lessons: [
          {
            id: "lesson_003_002_001",
            title: "JWT Authentication",
            description: "Implement token-based authentication",
            duration: "38m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_002_001_001",
                type: "video",
                title: "JWT Implementation",
                url: "https://www.youtube.com/watch?v=mbsmsi7l3r4",
                duration: "32m",
              },
              {
                id: "material_003_002_001_002",
                type: "document",
                title: "JWT Security Guide",
                url: "https://jwt.io/introduction",
              },
            ],
          },
          {
            id: "lesson_003_002_002",
            title: "API Security Best Practices",
            description: "Rate limiting, CORS, and security headers",
            duration: "30m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_002_002_001",
                type: "video",
                title: "API Security",
                url: "https://www.youtube.com/watch?v=2jqok-WgelI",
                duration: "24m",
              },
              {
                id: "material_003_002_002_002",
                type: "quiz",
                title: "Security Quiz",
                url: "https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html",
                questionsCount: 12,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_003_003",
        title: "Database and Prisma",
        description: "Advanced database patterns with Prisma ORM",
        order: 3,
        lessons: [
          {
            id: "lesson_003_003_001",
            title: "Prisma Setup and Schema Design",
            description: "Setting up Prisma with PostgreSQL",
            duration: "35m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_001_001",
                type: "video",
                title: "Prisma Introduction",
                url: "https://www.youtube.com/watch?v=RebA5J-rlwg",
                duration: "28m",
              },
              {
                id: "material_003_003_001_002",
                type: "document",
                title: "Schema Design Patterns",
                url: "https://www.prisma.io/docs/concepts/components/prisma-schema",
              },
            ],
          },
          {
            id: "lesson_003_003_002",
            title: "Advanced Queries and Relations",
            description: "Complex queries and relationship handling",
            duration: "40m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_002_001",
                type: "video",
                title: "Advanced Prisma",
                url: "https://www.youtube.com/watch?v=CYH04BJzamo",
                duration: "34m",
              },
              {
                id: "material_003_003_002_002",
                type: "exercise",
                title: "Query Practice",
                url: "https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries",
              },
            ],
          },
          {
            id: "lesson_003_003_003",
            title: "Transactions and Performance",
            description: "Optimize database operations",
            duration: "32m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_003_001",
                type: "video",
                title: "Database Optimization",
                url: "https://www.youtube.com/watch?v=dWYWtMqMduY",
                duration: "26m",
              },
              {
                id: "material_003_003_003_002",
                type: "document",
                title: "Performance Guide",
                url: "https://www.prisma.io/docs/guides/performance-and-optimization",
              },
            ],
          },
          {
            id: "lesson_003_003_004",
            title: "Migrations and Seeding",
            description: "Manage database schema changes",
            duration: "28m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_004_001",
                type: "video",
                title: "Prisma Migrations",
                url: "https://www.youtube.com/watch?v=_VPFzbtl9yM",
                duration: "22m",
              },
              {
                id: "material_003_003_004_002",
                type: "exercise",
                title: "Migration Practice",
                url: "https://www.prisma.io/docs/concepts/components/prisma-migrate",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_003_004",
        title: "Testing and Deployment",
        description: "Automated testing and production deployment",
        order: 4,
        lessons: [
          {
            id: "lesson_003_004_001",
            title: "Unit and Integration Testing",
            description: "Test your APIs with Jest and Supertest",
            duration: "45m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_004_001_001",
                type: "video",
                title: "Testing Strategies",
                url: "https://www.youtube.com/watch?v=r9HdJ8P6GQI",
                duration: "38m",
              },
              {
                id: "material_003_004_001_002",
                type: "code",
                title: "Test Examples",
                url: "https://github.com/testjavascript/nodejs-integration-tests-best-practices",
              },
            ],
          },
          {
            id: "lesson_003_004_002",
            title: "CI/CD Pipelines",
            description: "Automate testing and deployment",
            duration: "38m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_004_002_001",
                type: "video",
                title: "CI/CD Setup",
                url: "https://www.youtube.com/watch?v=scEDHsr3APg",
                duration: "32m",
              },
              {
                id: "material_003_004_002_002",
                type: "exercise",
                title: "Pipeline Configuration",
                url: "https://docs.github.com/en/actions/quickstart",
              },
            ],
          },
          {
            id: "lesson_003_004_003",
            title: "Production Deployment",
            description: "Deploy to cloud platforms",
            duration: "42m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_004_003_001",
                type: "video",
                title: "Deployment Guide",
                url: "https://www.youtube.com/watch?v=kBKIv1fPQlE",
                duration: "35m",
              },
              {
                id: "material_003_004_003_002",
                type: "document",
                title: "Production Checklist",
                url: "https://github.com/goldbergyoni/nodebestpractices#6-going-to-production-practices",
              },
              {
                id: "material_003_004_003_003",
                type: "quiz",
                title: "Final Assessment",
                url: "https://nodejs.org/en/docs/guides/",
                questionsCount: 20,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_005",
    title: "Docker & DevOps Fundamentals",
    subtitle:
      "Deploy applications like a pro using Docker, CI/CD, and cloud tooling",
    description:
      "Learn containerization, CI/CD pipelines, production workflows, and deployment best practices.",
    instructor: {
      name: "Alex Johnson",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    },
    thumbnail: "https://images.unsplash.com/photo-1527430253228-e93688616381",
    duration: "5h 50m",
    difficulty: "Intermediate",
    categories: ["DevOps", "Docker", "Cloud"],
    level: 2,
    studentsEnrolled: 2700,
    rating: 4.8,
    tags: ["docker", "ci/cd", "cloud", "devops"],
    updatedAt: "2025-10-01T12:00:00Z",
    isFree: false,
    price: { amount: 59.99, currency: "USD" },
    progress: 45,
    chapters: [
      {
        id: "chapter_005_001",
        title: "Docker Fundamentals",
        description: "Master containerization with Docker",
        order: 1,
        lessons: [
          {
            id: "lesson_005_001_001",
            title: "Introduction to Containers",
            description: "Understanding containerization concepts",
            duration: "20m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_005_001_001_001",
                type: "video",
                title: "Container Basics",
                url: "https://www.youtube.com/watch?v=pg19Z8LL06w",
                duration: "15m",
              },
              {
                id: "material_005_001_001_002",
                type: "document",
                title: "Docker Overview",
                url: "https://docs.docker.com/get-started/",
              },
            ],
          },
          {
            id: "lesson_005_001_002",
            title: "Dockerfile Best Practices",
            description: "Write efficient Dockerfiles",
            duration: "28m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_005_001_002_001",
                type: "video",
                title: "Dockerfile Optimization",
                url: "https://www.youtube.com/watch?v=8vXoMqWgbQQ",
                duration: "22m",
              },
              {
                id: "material_005_001_002_002",
                type: "code",
                title: "Dockerfile Examples",
                url: "https://docs.docker.com/develop/dev-best-practices/",
              },
            ],
          },
          {
            id: "lesson_005_001_003",
            title: "Docker Compose",
            description: "Multi-container applications",
            duration: "32m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_001_003_001",
                type: "video",
                title: "Docker Compose Guide",
                url: "https://www.youtube.com/watch?v=Qw9zlE3t8Ko",
                duration: "26m",
              },
              {
                id: "material_005_001_003_002",
                type: "exercise",
                title: "Compose Practice",
                url: "https://docs.docker.com/compose/gettingstarted/",
              },
            ],
          },
          {
            id: "lesson_005_001_004",
            title: "Docker Volumes and Networking",
            description: "Persist data and connect containers",
            duration: "24m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_001_004_001",
                type: "video",
                title: "Volumes and Networks",
                url: "https://www.youtube.com/watch?v=Gjnup-PuquQ",
                duration: "20m",
              },
              {
                id: "material_005_001_004_002",
                type: "code",
                title: "Network Examples",
                url: "https://docs.docker.com/network/",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_005_002",
        title: "CI/CD Pipelines",
        description: "Automate your deployment workflow",
        order: 2,
        lessons: [
          {
            id: "lesson_005_002_001",
            title: "GitHub Actions Basics",
            description: "Set up automated workflows",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_002_001_001",
                type: "video",
                title: "GitHub Actions Tutorial",
                url: "https://www.youtube.com/watch?v=R8_veQiYBjI",
                duration: "24m",
              },
              {
                id: "material_005_002_001_002",
                type: "code",
                title: "Workflow Templates",
                url: "https://github.com/sdras/awesome-actions",
              },
            ],
          },
          {
            id: "lesson_005_002_002",
            title: "Testing in CI/CD",
            description: "Automated testing pipelines",
            duration: "35m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_002_002_001",
                type: "video",
                title: "CI Testing Strategies",
                url: "https://www.youtube.com/watch?v=tMESFF5sVlU",
                duration: "28m",
              },
              {
                id: "material_005_002_002_002",
                type: "exercise",
                title: "Build Pipeline",
                url: "https://docs.github.com/en/actions/automating-builds-and-tests",
              },
            ],
          },
          {
            id: "lesson_005_002_003",
            title: "Production Deployments",
            description: "Deploy to cloud platforms with confidence",
            duration: "42m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_002_003_001",
                type: "video",
                title: "Deployment Strategies",
                url: "https://www.youtube.com/watch?v=eB0nUzAI7M8",
                duration: "36m",
              },
              {
                id: "material_005_002_003_002",
                type: "document",
                title: "Deployment Checklist",
                url: "https://github.com/mtdvio/going-to-production",
              },
              {
                id: "material_005_002_003_003",
                type: "quiz",
                title: "DevOps Final Quiz",
                url: "https://roadmap.sh/devops",
                questionsCount: 18,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_006",
    title: "SQL & Database Design",
    subtitle:
      "Master Postgres, indexing, schema design, and real production patterns",
    description:
      "A complete guide to relational databases, Postgres, optimization, and schema architecture.",
    instructor: {
      name: "Nadia Hassan",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    },
    thumbnail: "https://images.unsplash.com/photo-1559526324-593bc073d938",
    duration: "6h 05m",
    difficulty: "Intermediate",
    categories: ["Databases", "SQL", "Backend"],
    level: 2,
    studentsEnrolled: 1890,
    rating: 4.7,
    tags: ["sql", "postgres", "schema"],
    updatedAt: "2025-09-15T12:00:00Z",
    isFree: false,
    price: { amount: 54.0, currency: "USD" },
    progress: 80,
    chapters: [
      {
        id: "chapter_006_001",
        title: "SQL Fundamentals",
        description: "Master SQL queries and data manipulation",
        order: 1,
        lessons: [
          {
            id: "lesson_006_001_001",
            title: "SELECT Queries and Filtering",
            description: "Writing efficient SELECT statements",
            duration: "25m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_001_001",
                type: "video",
                title: "SQL Basics",
                url: "https://www.youtube.com/watch?v=5hzZtqCNQKk",
                duration: "20m",
              },
              {
                id: "material_006_001_001_002",
                type: "exercise",
                title: "Query Practice",
                url: "https://www.sqlteaching.com/",
              },
            ],
          },
          {
            id: "lesson_006_001_002",
            title: "JOINs and Relationships",
            description: "Combining data from multiple tables",
            duration: "30m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_002_001",
                type: "video",
                title: "Understanding JOINs",
                url: "https://www.youtube.com/watch?v=9yeOJ0ZMUYw",
                duration: "24m",
              },
              {
                id: "material_006_001_002_002",
                type: "code",
                title: "JOIN Examples",
                url: "https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-joins/",
              },
            ],
          },
          {
            id: "lesson_006_001_003",
            title: "Aggregations and GROUP BY",
            description: "Analyzing data with aggregate functions",
            duration: "28m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_003_001",
                type: "video",
                title: "Aggregation Functions",
                url: "https://www.youtube.com/watch?v=tMcOMdULldg",
                duration: "22m",
              },
              {
                id: "material_006_001_003_002",
                type: "quiz",
                title: "SQL Basics Quiz",
                url: "https://www.postgresql.org/docs/current/tutorial-agg.html",
                questionsCount: 10,
              },
            ],
          },
          {
            id: "lesson_006_001_004",
            title: "Subqueries and CTEs",
            description: "Advanced query techniques",
            duration: "34m",
            order: 4,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_004_001",
                type: "video",
                title: "Complex Queries",
                url: "https://www.youtube.com/watch?v=XQ_6G4kj_xk",
                duration: "28m",
              },
              {
                id: "material_006_001_004_002",
                type: "exercise",
                title: "Advanced Query Practice",
                url: "https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-cte/",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_006_002",
        title: "Database Design",
        description: "Schema design and normalization",
        order: 2,
        lessons: [
          {
            id: "lesson_006_002_001",
            title: "Normalization Principles",
            description: "Design normalized database schemas",
            duration: "32m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_002_001_001",
                type: "video",
                title: "Database Normalization",
                url: "https://www.youtube.com/watch?v=GFQaEYEc8_8",
                duration: "26m",
              },
              {
                id: "material_006_002_001_002",
                type: "document",
                title: "Normal Forms Guide",
                url: "https://www.postgresql.org/docs/current/tutorial-concepts.html",
              },
            ],
          },
          {
            id: "lesson_006_002_002",
            title: "Indexes and Performance",
            description: "Optimize queries with proper indexing",
            duration: "35m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_002_002_001",
                type: "video",
                title: "Index Optimization",
                url: "https://www.youtube.com/watch?v=rKlKLkD1akI",
                duration: "28m",
              },
              {
                id: "material_006_002_002_002",
                type: "exercise",
                title: "Index Practice",
                url: "https://www.postgresqltutorial.com/postgresql-indexes/",
              },
            ],
          },
          {
            id: "lesson_006_002_003",
            title: "Views and Stored Procedures",
            description: "Encapsulate complex logic",
            duration: "29m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_002_003_001",
                type: "video",
                title: "Views and Procedures",
                url: "https://www.youtube.com/watch?v=xaWlS9HtWYw",
                duration: "24m",
              },
              {
                id: "material_006_002_003_002",
                type: "code",
                title: "Procedure Examples",
                url: "https://www.postgresql.org/docs/current/sql-createview.html",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_006_003",
        title: "Advanced PostgreSQL",
        description: "PostgreSQL-specific features",
        order: 3,
        lessons: [
          {
            id: "lesson_006_003_001",
            title: "Advanced Data Types",
            description: "JSON, arrays, and custom types",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_003_001_001",
                type: "video",
                title: "Postgres Data Types",
                url: "https://www.youtube.com/watch?v=1VVlBqYpImM",
                duration: "24m",
              },
              {
                id: "material_006_003_001_002",
                type: "code",
                title: "Type Examples",
                url: "https://www.postgresql.org/docs/current/datatype.html",
              },
            ],
          },
          {
            id: "lesson_006_003_002",
            title: "Transactions and Concurrency",
            description: "Managing concurrent database access",
            duration: "38m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_003_002_001",
                type: "video",
                title: "Transaction Management",
                url: "https://www.youtube.com/watch?v=D0L49xnJNLk",
                duration: "32m",
              },
              {
                id: "material_006_003_002_002",
                type: "quiz",
                title: "Advanced PostgreSQL Quiz",
                url: "https://www.postgresql.org/docs/current/tutorial-transactions.html",
                questionsCount: 12,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_006_004",
        title: "Production Database Management",
        description: "Manage databases at scale",
        order: 4,
        lessons: [
          {
            id: "lesson_006_004_001",
            title: "Backup and Recovery",
            description: "Protect your data",
            duration: "27m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_004_001_001",
                type: "video",
                title: "Backup Strategies",
                url: "https://www.youtube.com/watch?v=0GvMsXyGp6U",
                duration: "22m",
              },
              {
                id: "material_006_004_001_002",
                type: "document",
                title: "Recovery Procedures",
                url: "https://www.postgresql.org/docs/current/backup.html",
              },
            ],
          },
          {
            id: "lesson_006_004_002",
            title: "Monitoring and Maintenance",
            description: "Keep your database healthy",
            duration: "31m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_004_002_001",
                type: "video",
                title: "Database Monitoring",
                url: "https://www.youtube.com/watch?v=1aXk2nLVTw4",
                duration: "26m",
              },
              {
                id: "material_006_004_002_002",
                type: "exercise",
                title: "Maintenance Tasks",
                url: "https://www.postgresql.org/docs/current/maintenance.html",
              },
            ],
          },
          {
            id: "lesson_006_004_003",
            title: "Scaling Strategies",
            description: "Scale your database for growth",
            duration: "36m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_004_003_001",
                type: "video",
                title: "Database Scaling",
                url: "https://www.youtube.com/watch?v=dWL5gx_bop4",
                duration: "30m",
              },
              {
                id: "material_006_004_003_002",
                type: "quiz",
                title: "Final Database Quiz",
                url: "https://www.postgresql.org/docs/current/tutorial.html",
                questionsCount: 15,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_007",
    title: "Python for Data Analysis",
    subtitle:
      "Analyze datasets, visualize results, and build predictive insights",
    description:
      "Hands-on training using pandas, NumPy, Matplotlib, and practical data-cleaning workflows.",
    instructor: {
      name: "David Park",
      avatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91",
    },
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c",
    duration: "7h 15m",
    difficulty: "Intermediate",
    categories: ["Data Science", "Python"],
    level: 2,
    studentsEnrolled: 5200,
    rating: 4.9,
    tags: ["python", "data", "analysis", "pandas"],
    updatedAt: "2025-11-01T12:00:00Z",
    isFree: false,
    price: { amount: 79.0, currency: "USD" },
    progress: 50,
    chapters: [
      {
        id: "chapter_007_001",
        title: "Python and Pandas Basics",
        description: "Get started with data analysis in Python",
        order: 1,
        lessons: [
          {
            id: "lesson_007_001_001",
            title: "NumPy Fundamentals",
            description: "Working with arrays and numerical data",
            duration: "30m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_001_001",
                type: "video",
                title: "NumPy Introduction",
                url: "https://www.youtube.com/watch?v=QUT1VHiLmmI",
                duration: "24m",
              },
              {
                id: "material_007_001_001_002",
                type: "code",
                title: "NumPy Examples",
                url: "https://numpy.org/doc/stable/user/quickstart.html",
              },
            ],
          },
          {
            id: "lesson_007_001_002",
            title: "Pandas DataFrames",
            description: "Data manipulation with Pandas",
            duration: "35m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_002_001",
                type: "video",
                title: "Pandas Basics",
                url: "https://www.youtube.com/watch?v=vmEHCJofslg",
                duration: "28m",
              },
              {
                id: "material_007_001_002_002",
                type: "exercise",
                title: "DataFrame Practice",
                url: "https://pandas.pydata.org/docs/user_guide/10min.html",
              },
            ],
          },
          {
            id: "lesson_007_001_003",
            title: "Data Cleaning Techniques",
            description: "Handle missing data and outliers",
            duration: "32m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_003_001",
                type: "video",
                title: "Data Cleaning",
                url: "https://www.youtube.com/watch?v=KdmPHEnPJPs",
                duration: "26m",
              },
              {
                id: "material_007_001_003_002",
                type: "document",
                title: "Cleaning Best Practices",
                url: "https://pandas.pydata.org/docs/user_guide/missing_data.html",
              },
            ],
          },
          {
            id: "lesson_007_001_004",
            title: "Data Transformation",
            description: "Reshape and pivot data",
            duration: "29m",
            order: 4,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_004_001",
                type: "video",
                title: "Transform Data",
                url: "https://www.youtube.com/watch?v=vCFjGKy5IFI",
                duration: "24m",
              },
              {
                id: "material_007_001_004_002",
                type: "exercise",
                title: "Transformation Practice",
                url: "https://pandas.pydata.org/docs/user_guide/reshaping.html",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_007_002",
        title: "Data Visualization",
        description: "Create compelling visualizations",
        order: 2,
        lessons: [
          {
            id: "lesson_007_002_001",
            title: "Matplotlib Fundamentals",
            description: "Basic plotting with Matplotlib",
            duration: "28m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_002_001_001",
                type: "video",
                title: "Matplotlib Guide",
                url: "https://www.youtube.com/watch?v=DAQNHzOcO5A",
                duration: "22m",
              },
              {
                id: "material_007_002_001_002",
                type: "code",
                title: "Plot Examples",
                url: "https://matplotlib.org/stable/tutorials/introductory/pyplot.html",
              },
            ],
          },
          {
            id: "lesson_007_002_002",
            title: "Seaborn for Statistical Plots",
            description: "Advanced visualization with Seaborn",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_002_002_001",
                type: "video",
                title: "Seaborn Tutorial",
                url: "https://www.youtube.com/watch?v=6GUZXDef2U0",
                duration: "26m",
              },
              {
                id: "material_007_002_002_002",
                type: "exercise",
                title: "Visualization Project",
                url: "https://seaborn.pydata.org/tutorial.html",
              },
            ],
          },
          {
            id: "lesson_007_002_003",
            title: "Interactive Visualizations",
            description: "Create interactive plots with Plotly",
            duration: "27m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_002_003_001",
                type: "video",
                title: "Plotly Tutorial",
                url: "https://www.youtube.com/watch?v=hSPmj7mK6ng",
                duration: "22m",
              },
              {
                id: "material_007_002_003_002",
                type: "code",
                title: "Interactive Examples",
                url: "https://plotly.com/python/getting-started/",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_007_003",
        title: "Real-World Projects",
        description: "Apply your skills to real datasets",
        order: 3,
        lessons: [
          {
            id: "lesson_007_003_001",
            title: "Exploratory Data Analysis Project",
            description: "Analyze a complete dataset",
            duration: "50m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_003_001_001",
                type: "video",
                title: "EDA Walkthrough",
                url: "https://www.youtube.com/watch?v=_wNowdG0slc",
                duration: "42m",
              },
              {
                id: "material_007_003_001_002",
                type: "exercise",
                title: "Complete Analysis",
                url: "https://www.kaggle.com/learn/data-visualization",
              },
            ],
          },
          {
            id: "lesson_007_003_002",
            title: "Predictive Modeling Basics",
            description: "Build your first predictive model",
            duration: "45m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_003_002_001",
                type: "video",
                title: "Modeling Introduction",
                url: "https://www.youtube.com/watch?v=7eh4d6sabA0",
                duration: "38m",
              },
              {
                id: "material_007_003_002_002",
                type: "quiz",
                title: "Final Assessment",
                url: "https://scikit-learn.org/stable/tutorial/basic/tutorial.html",
                questionsCount: 18,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_008",
    title: "Startup Branding & Marketing",
    subtitle: "Build a brand identity that actually sells",
    description:
      "Learn positioning, brand design, content strategy, storytelling, and the modern marketing stack.",
    instructor: {
      name: "Laura Smith",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    },
    thumbnail: "https://images.unsplash.com/photo-1492724441997-5dc865305da7",
    duration: "2h 50m",
    difficulty: "Beginner",
    categories: ["Marketing", "Branding"],
    level: 1,
    studentsEnrolled: 3100,
    rating: 4.5,
    tags: ["branding", "marketing", "storytelling"],
    updatedAt: "2025-08-10T12:00:00Z",
    isFree: true,
    price: null,
    progress: 90,
    chapters: [
      {
        id: "chapter_008_001",
        title: "Brand Foundations",
        description: "Build a strong brand identity",
        order: 1,
        lessons: [
          {
            id: "lesson_008_001_001",
            title: "Finding Your Brand Position",
            description: "Define your unique market position",
            duration: "22m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_001_001",
                type: "video",
                title: "Brand Positioning",
                url: "https://www.youtube.com/watch?v=iHuDlB7tDhM",
                duration: "18m",
              },
              {
                id: "material_008_001_001_002",
                type: "document",
                title: "Positioning Worksheet",
                url: "https://www.strategyzer.com/canvas/value-proposition-canvas",
              },
            ],
          },
          {
            id: "lesson_008_001_002",
            title: "Crafting Your Brand Story",
            description: "Storytelling for startups",
            duration: "20m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_002_001",
                type: "video",
                title: "Brand Storytelling",
                url: "https://www.youtube.com/watch?v=yPvuhJZ0ftU",
                duration: "16m",
              },
              {
                id: "material_008_001_002_002",
                type: "exercise",
                title: "Story Framework",
                url: "https://www.storybrands.com/",
              },
            ],
          },
          {
            id: "lesson_008_001_003",
            title: "Visual Identity Design",
            description: "Create a memorable visual brand",
            duration: "25m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_003_001",
                type: "video",
                title: "Design Fundamentals",
                url: "https://www.youtube.com/watch?v=RBq4E_HAw8Y",
                duration: "20m",
              },
              {
                id: "material_008_001_003_002",
                type: "document",
                title: "Design Guidelines",
                url: "https://www.canva.com/learn/brand-identity/",
              },
            ],
          },
          {
            id: "lesson_008_001_004",
            title: "Brand Voice and Messaging",
            description: "Develop your unique brand voice",
            duration: "21m",
            order: 4,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_004_001",
                type: "video",
                title: "Voice and Tone",
                url: "https://www.youtube.com/watch?v=XWu8f8khMFY",
                duration: "16m",
              },
              {
                id: "material_008_001_004_002",
                type: "exercise",
                title: "Voice Workshop",
                url: "https://mailchimp.com/resources/brand-voice/",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_008_002",
        title: "Content Strategy",
        description: "Create content that converts",
        order: 2,
        lessons: [
          {
            id: "lesson_008_002_001",
            title: "Content Marketing Fundamentals",
            description: "Build a content strategy",
            duration: "24m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_002_001_001",
                type: "video",
                title: "Content Strategy",
                url: "https://www.youtube.com/watch?v=S3HhGxuEhWw",
                duration: "20m",
              },
              {
                id: "material_008_002_001_002",
                type: "exercise",
                title: "Content Calendar",
                url: "https://contentmarketinginstitute.com/content-marketing-strategy/",
              },
            ],
          },
          {
            id: "lesson_008_002_002",
            title: "Social Media Marketing",
            description: "Grow your audience on social platforms",
            duration: "26m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_002_002_001",
                type: "video",
                title: "Social Media Guide",
                url: "https://www.youtube.com/watch?v=jHTuJ1q2xFU",
                duration: "22m",
              },
              {
                id: "material_008_002_002_002",
                type: "quiz",
                title: "Marketing Quiz",
                url: "https://www.hubspot.com/marketing-statistics",
                questionsCount: 8,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_008_003",
        title: "Growth and Analytics",
        description: "Measure and optimize your marketing",
        order: 3,
        lessons: [
          {
            id: "lesson_008_003_001",
            title: "Marketing Analytics",
            description: "Track and measure marketing performance",
            duration: "20m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_008_003_001_001",
                type: "video",
                title: "Analytics Basics",
                url: "https://www.youtube.com/watch?v=T3HKBpAU9lk",
                duration: "16m",
              },
              {
                id: "material_008_003_001_002",
                type: "document",
                title: "Metrics Guide",
                url: "https://analytics.google.com/analytics/academy/",
              },
            ],
          },
          {
            id: "lesson_008_003_002",
            title: "Growth Hacking Strategies",
            description: "Scale your startup marketing",
            duration: "22m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_008_003_002_001",
                type: "video",
                title: "Growth Tactics",
                url: "https://www.youtube.com/watch?v=N8qGUFxfG2g",
                duration: "18m",
              },
              {
                id: "material_008_003_002_002",
                type: "quiz",
                title: "Final Marketing Quiz",
                url: "https://www.growthhackers.com/",
                questionsCount: 10,
              },
            ],
          },
        ],
      },
    ],
  },
] as const;

export const quizObject = {
  id: "quiz_001",
  title: "React Fundamentals Assessment",
  description: "Test your knowledge of React basics, hooks, and component patterns",
  duration: "30m",
  totalQuestions: 8,
  passingScore: 70,
  questions: [
    {
      id: "q1",
      type: "multiple-choice",
      question: "What is the correct way to update state in a functional component?",
      points: 10,
      options: [
        { id: "a", text: "this.setState({ count: 1 })", isCorrect: false },
        { id: "b", text: "setState({ count: 1 })", isCorrect: false },
        { id: "c", text: "setCount(1)", isCorrect: true },
        { id: "d", text: "updateState(count, 1)", isCorrect: false },
      ],
      explanation:
        "In functional components, you use the setter function returned by useState hook (e.g., setCount) to update state.",
    },
    {
      id: "q2",
      type: "true-false",
      question:
        "React components must always return a single root element or fragment.",
      points: 5,
      correctAnswer: true,
      explanation:
        "React components must return a single root element. You can use fragments (<></>) to avoid adding extra DOM nodes.",
    },
    {
      id: "q3",
      type: "multiple-choice",
      question:
        "Which hook should you use to perform side effects in a functional component?",
      points: 10,
      options: [
        { id: "a", text: "useState", isCorrect: false },
        { id: "b", text: "useEffect", isCorrect: true },
        { id: "c", text: "useContext", isCorrect: false },
        { id: "d", text: "useReducer", isCorrect: false },
      ],
      explanation:
        "useEffect is the hook for handling side effects like data fetching, subscriptions, or manually changing the DOM.",
    },
    {
      id: "q4",
      type: "multiple-select",
      question:
        "Which of the following are valid ways to pass data in React? (Select all that apply)",
      points: 15,
      options: [
        { id: "a", text: "Props from parent to child", isCorrect: true },
        { id: "b", text: "Context API", isCorrect: true },
        { id: "c", text: "Direct state mutation", isCorrect: false },
        { id: "d", text: "Callback functions", isCorrect: true },
        { id: "e", text: "Global variables", isCorrect: false },
      ],
      explanation:
        "Data can be passed via props, Context API, and callback functions. Direct state mutation and global variables are anti-patterns in React.",
    },
    {
      id: "q5",
      type: "code-completion",
      question: "Complete the useState hook to manage a counter starting at 0:",
      points: 15,
      code: "const [count, setCount] = ______(0);",
      correctAnswer: "useState",
      alternatives: ["React.useState"],
      explanation:
        "The useState hook is used to add state to functional components. It takes the initial state value as an argument.",
    },
    {
      id: "q6",
      type: "ordering",
      question:
        "Arrange the React component lifecycle phases in the correct order:",
      points: 15,
      items: [
        { id: "1", text: "Mounting", correctOrder: 1 },
        { id: "2", text: "Updating", correctOrder: 2 },
        { id: "3", text: "Unmounting", correctOrder: 3 },
      ],
      explanation:
        "React components go through three main phases: Mounting (initial render), Updating (re-renders), and Unmounting (cleanup).",
    },
    {
      id: "q7",
      type: "matching",
      question: "Match each React hook with its primary use case:",
      points: 20,
      pairs: [
        { id: "1", left: "useState", right: "Managing component state" },
        { id: "2", left: "useEffect", right: "Handling side effects" },
        { id: "3", left: "useContext", right: "Accessing context values" },
        { id: "4", left: "useMemo", right: "Memoizing computed values" },
      ],
      explanation:
        "Each React hook serves a specific purpose in managing different aspects of component behavior and optimization.",
    },
    {
      id: "q8",
      type: "short-answer",
      question:
        "What is the purpose of the dependency array in useEffect? (Answer in 1-2 sentences)",
      points: 10,
      sampleAnswer:
        "The dependency array controls when the effect runs. The effect only re-runs when one of the dependencies changes between renders.",
      keywords: ["dependency", "dependencies", "changes", "re-run", "control"],
      explanation:
        "The dependency array is the second argument to useEffect and determines when the effect should re-execute based on value changes.",
    },
  ],
} as const;
