export const courses = [
  {
    id: "course_001",
    title: "Introduction à Golang",
    subtitle:
      "Apprenez les fondamentaux de Go en construisant de vrais projets",
    description:
      "Un cours pour débutants enseignant les concepts clés de Go, dont la syntaxe, la concurrence et la création d’API simples.",
    instructor: {
      name: "John Doe",
      avatar: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    },
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    duration: "6h 30m",
    difficulty: "Débutant",
    categories: ["Programmation", "Développement backend", "Golang"],
    level: 1,
    studentsEnrolled: 1275,
    rating: 4.8,
    tags: ["go", "backend", "api", "concurrency"],
    updatedAt: "2025-10-10T12:00:00Z",
    isFree: false,
    price: { amount: 49.99, currency: "USD" },
    progress: 65,
    chapters: [
      {
        id: "chapter_001_001",
        title: "Bien démarrer avec Go",
        description: "Introduction à la syntaxe Go et aux concepts de base",
        order: 1,
        lessons: [
          {
            completed: true,
            id: "lesson_001_001_001",
            title: "Installer Go et configurer votre environnement",
            description:
              "Apprenez à installer Go et à configurer votre environnement de développement",
            duration: "12m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_001_001_001_001",
                type: "video",
                title: "Guide d’installation",
                url: "https://www.youtube.com/embed/YS4e4q9oBaU",
                duration: "8m",
              },
              {
                id: "material_001_001_001_002",
                type: "video",
                title: "Configurer VS Code pour Go",
                url: "https://www.youtube.com/embed/1MXIGYrMk80",
                duration: "12m",
              },
              {
                id: "material_001_001_001_003",
                type: "document",
                title: "Documentation du langage Go",
                url: "https://pdfobject.com/pdf/sample.pdf",
                duration: "15m",
              },
              {
                id: "material_001_001_001_004",
                type: "document",
                title: "Liste de vérification d’installation",
                url: "https://go.dev/doc/install",
                duration: "5m",
              },
              {
                id: "material_001_001_001_005",
                type: "code",
                title: "Exemples de démarrage rapide",
                url: "https://go.dev/play/",
              },
              {
                id: "material_001_001_001_006",
                type: "exercise",
                title: "Vérifier votre installation",
                url: "https://go.dev/tour/welcome/1",
              },
              {
                id: "material_001_001_001_007",
                type: "link",
                title: "Site officiel de Go",
                url: "https://go.dev",
              },
              {
                id: "material_001_001_001_008",
                type: "document",
                title: "Résolution des problèmes courants",
                url: "https://go.dev/doc/install/source",
                duration: "8m",
              },
              {
                id: "material_001_001_001_009",
                type: "quiz",
                title: "Quiz d’installation de l’environnement",
                url: "https://go.dev/tour/welcome/1",
                questionsCount: 5,
              },
            ],
          },
          {
            id: "lesson_001_001_002",
            title: "Votre premier programme Go",
            description: "Écrire et exécuter votre premier Hello World en Go",
            duration: "15m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_001_002_001",
                type: "video",
                title: "Tutoriel Hello World",
                url: "https://www.youtube.com/embed/446E-r0rXHI",
                duration: "10m",
              },
              {
                id: "material_001_001_002_002",
                type: "code",
                title: "Code de démarrage",
                url: "https://go.dev/play/p/fvVu6MpBCMi",
              },
              {
                id: "material_001_001_002_003",
                type: "exercise",
                title: "Exercice pratique : variables",
                url: "https://exercism.org/tracks/go/exercises/hello-world",
              },
            ],
          },
          {
            id: "lesson_001_001_003",
            title: "Comprendre l’espace de travail et les modules Go",
            description:
              "Découvrez les modules Go, la structure de l’espace de travail et la gestion des dépendances",
            duration: "18m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_001_003_001",
                type: "video",
                title: "Modules Go expliqués",
                url: "https://www.youtube.com/embed/Z1VhG7cf83M",
                duration: "12m",
              },
              {
                id: "material_001_001_003_002",
                type: "document",
                title: "Référence des modules Go",
                url: "https://pdfobject.com/pdf/sample.pdf",
                duration: "8m",
              },
              {
                id: "material_001_001_003_003",
                type: "code",
                title: "Exemples de modules",
                url: "https://go.dev/play/",
              },
            ],
          },
          {
            id: "lesson_001_001_004",
            title: "Outils Go et commandes CLI",
            description:
              "Maîtriser les outils en ligne de commande essentiels de Go",
            duration: "14m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_001_004_001",
                type: "video",
                title: "Aperçu des outils CLI Go",
                url: "https://www.youtube.com/embed/XCsL89YtqCs",
                duration: "10m",
              },
              {
                id: "material_001_001_004_002",
                type: "document",
                title: "Guide de référence des commandes",
                url: "https://go.dev/doc/",
                duration: "6m",
              },
            ],
          },
          {
            id: "lesson_001_001_005",
            title: "Syntaxe et structure de base de Go",
            description:
              "Comprendre les règles de syntaxe fondamentales et la structure des programmes en Go",
            duration: "20m",
            order: 5,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_001_005_001",
                type: "video",
                title: "Bases de la syntaxe Go",
                url: "https://www.youtube.com/embed/YS4e4q9oBaU",
                duration: "14m",
              },
              {
                id: "material_001_001_005_002",
                type: "code",
                title: "Exemples de syntaxe",
                url: "https://gobyexample.com/",
              },
              {
                id: "material_001_001_005_003",
                type: "exercise",
                title: "Exercices de syntaxe",
                url: "https://go.dev/tour/basics/1",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_002",
        title: "Fondamentaux de Go",
        description: "Approfondissement des fonctionnalités clés de Go",
        order: 2,
        lessons: [
          {
            id: "lesson_001_002_001",
            title: "Variables et types de données",
            description: "Comprendre le système de types de Go",
            duration: "20m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_001_001",
                type: "video",
                title: "Types de données expliqués",
                url: "https://www.youtube.com/watch?v=pM0-CMysa_M",
                duration: "15m",
              },
              {
                id: "material_001_002_001_002",
                type: "document",
                title: "Référence du système de types",
                url: "https://go.dev/ref/spec#Types",
              },
            ],
          },
          {
            id: "lesson_001_002_002",
            title: "Structures de contrôle",
            description:
              "Apprenez if‑else, les boucles et les instructions switch en Go",
            duration: "25m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_002_001",
                type: "video",
                title: "Flux de contrôle en Go",
                url: "https://www.youtube.com/watch?v=X2WS5pKnk3M",
                duration: "18m",
              },
              {
                id: "material_001_002_002_002",
                type: "exercise",
                title: "Exercices de boucles",
                url: "https://go.dev/tour/flowcontrol/1",
              },
            ],
          },
          {
            id: "lesson_001_002_003",
            title: "Fonctions et méthodes",
            description:
              "Maîtriser les fonctions, les méthodes et les receivers",
            duration: "30m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_003_001",
                type: "video",
                title: "Approfondissement des fonctions",
                url: "https://www.youtube.com/watch?v=rr7tM5_V7QQ",
                duration: "22m",
              },
              {
                id: "material_001_002_003_002",
                type: "code",
                title: "Exemples de méthodes",
                url: "https://gobyexample.com/methods",
              },
            ],
          },
          {
            id: "lesson_001_002_004",
            title: "Structs et pointeurs",
            description: "Travailler avec les structs et les pointeurs",
            duration: "27m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_004_001",
                type: "video",
                title: "Structs expliqués",
                url: "https://www.youtube.com/watch?v=v9FHhHMH430",
                duration: "20m",
              },
              {
                id: "material_001_002_004_002",
                type: "exercise",
                title: "Pratique des structs",
                url: "https://gobyexample.com/structs",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_003",
        title: "Concepts avancés de Go",
        description:
          "Maîtriser la concurrence, les interfaces et la gestion des erreurs",
        order: 3,
        lessons: [
          {
            id: "lesson_001_003_001",
            title: "Goroutines et channels",
            description: "Comprendre le modèle de concurrence de Go",
            duration: "35m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_003_001_001",
                type: "video",
                title: "Fondamentaux de la concurrence",
                url: "https://www.youtube.com/watch?v=LvgVSSpwND8",
                duration: "28m",
              },
              {
                id: "material_001_003_001_002",
                type: "exercise",
                title: "Pratique des goroutines",
                url: "https://gobyexample.com/goroutines",
              },
            ],
          },
          {
            id: "lesson_001_003_002",
            title: "Interfaces et assertions de type",
            description: "Polymorphisme en Go",
            duration: "28m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_003_002_001",
                type: "video",
                title: "Comprendre les interfaces",
                url: "https://www.youtube.com/watch?v=qJKQZKGZgf0",
                duration: "20m",
              },
              {
                id: "material_001_003_002_002",
                type: "document",
                title: "Schémas d’interfaces",
                url: "https://go.dev/tour/methods/9",
              },
            ],
          },
          {
            id: "lesson_001_003_003",
            title: "Bonnes pratiques de gestion des erreurs",
            description:
              "Gestion correcte des erreurs dans les applications Go",
            duration: "22m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_003_003_001",
                type: "video",
                title: "Schémas de gestion des erreurs",
                url: "https://www.youtube.com/watch?v=6YM5WkF9A0c",
                duration: "18m",
              },
              {
                id: "material_001_003_003_002",
                type: "quiz",
                title: "Quiz : gestion des erreurs",
                url: "https://go.dev/blog/error-handling-and-go",
                questionsCount: 8,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_004",
        title: "Construire des API REST",
        description: "Créer des API prêtes pour la production avec Go",
        order: 4,
        lessons: [
          {
            id: "lesson_001_004_001",
            title: "Bases du serveur HTTP",
            description: "Construire votre premier serveur HTTP",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_004_001_001",
                type: "video",
                title: "Configuration du serveur HTTP",
                url: "https://www.youtube.com/watch?v=oy1mPiW_d2E",
                duration: "25m",
              },
              {
                id: "material_001_004_001_002",
                type: "code",
                title: "Modèle de serveur",
                url: "https://gobyexample.com/http-servers",
              },
            ],
          },
          {
            id: "lesson_001_004_002",
            title: "Routage et middleware",
            description:
              "Implémenter des schémas de routage et des middlewares",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_004_002_001",
                type: "video",
                title: "Routage avec Gorilla Mux",
                url: "https://www.youtube.com/watch?v=vXtf9nJygXs",
                duration: "26m",
              },
              {
                id: "material_001_004_002_002",
                type: "exercise",
                title: "Construire une API REST",
                url: "https://github.com/gorilla/mux#examples",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_005",
        title: "Tests et bonnes pratiques",
        description: "Écrire des tests et suivre les conventions Go",
        order: 5,
        lessons: [
          {
            id: "lesson_001_005_001",
            title: "Écrire des tests unitaires",
            description: "Tester efficacement votre code Go",
            duration: "33m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_005_001_001",
                type: "video",
                title: "Tests en Go",
                url: "https://www.youtube.com/watch?v=prjjXD2xYKE",
                duration: "26m",
              },
              {
                id: "material_001_005_001_002",
                type: "code",
                title: "Exemples de tests",
                url: "https://gobyexample.com/testing",
              },
            ],
          },
          {
            id: "lesson_001_005_002",
            title: "Projet final",
            description:
              "Construire une API REST complète avec base de données",
            duration: "55m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_005_002_001",
                type: "video",
                title: "Présentation du projet",
                url: "https://www.youtube.com/watch?v=XCsL89YtqCs",
                duration: "48m",
              },
              {
                id: "material_001_005_002_002",
                type: "exercise",
                title: "Projet API complet",
                url: "https://github.com/mactsouk/rest-api",
              },
              {
                id: "material_001_005_002_003",
                type: "quiz",
                title: "Évaluation finale",
                url: "https://go.dev/tour/list",
                questionsCount: 20,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_002",
    title: "React pour débutants",
    subtitle:
      "Construisez des interfaces dynamiques avec React moderne et les Hooks",
    description:
      "Apprenez à construire des interfaces évolutives avec React, les Hooks, l’API Context et des composants réutilisables.",
    instructor: {
      name: "Emily Carter",
      avatar: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39",
    },
    thumbnail: "https://images.unsplash.com/photo-1587620962725-abab7fe55159",
    duration: "4h 45m",
    difficulty: "Débutant",
    categories: ["Front‑end", "JavaScript", "React"],
    level: 1,
    studentsEnrolled: 3400,
    rating: 4.7,
    tags: ["react", "frontend", "hooks"],
    updatedAt: "2025-09-18T12:00:00Z",
    isFree: true,
    price: null,
    progress: 30,
    chapters: [
      {
        id: "chapter_002_001",
        title: "Bases de React",
        description: "Introduction aux composants React et à JSX",
        order: 1,
        lessons: [
          {
            id: "lesson_002_001_001",
            title: "Qu’est‑ce que React ?",
            description: "Comprendre React et son écosystème",
            duration: "18m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_002_001_001_001",
                type: "video",
                title: "Introduction à React",
                url: "https://www.youtube.com/watch?v=Tn6-PIqc4UM",
                duration: "12m",
              },
              {
                id: "material_002_001_001_002",
                type: "document",
                title: "Vue d’ensemble de React",
                url: "https://react.dev/learn",
              },
              {
                id: "material_002_001_001_003",
                type: "link",
                title: "Documentation officielle de React",
                url: "https://react.dev",
              },
            ],
          },
          {
            id: "lesson_002_001_002",
            title: "Principes fondamentaux de JSX",
            description: "Apprendre la syntaxe JSX et les bonnes pratiques",
            duration: "22m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_002_001_002_001",
                type: "video",
                title: "Approfondissement de JSX",
                url: "https://www.youtube.com/watch?v=kVeOpcw4GWY",
                duration: "16m",
              },
              {
                id: "material_002_001_002_002",
                type: "code",
                title: "Exemples de JSX",
                url: "https://react.dev/learn/writing-markup-with-jsx",
              },
            ],
          },
          {
            id: "lesson_002_001_003",
            title: "Composants et props",
            description:
              "Construire des composants réutilisables avec des props",
            duration: "26m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_001_003_001",
                type: "video",
                title: "Composition de composants",
                url: "https://www.youtube.com/watch?v=5yPdXnSyuRM",
                duration: "20m",
              },
              {
                id: "material_002_001_003_002",
                type: "exercise",
                title: "Construire des composants",
                url: "https://react.dev/learn/passing-props-to-a-component",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_002",
        title: "État et cycle de vie",
        description:
          "Gérer l’état des composants et les méthodes du cycle de vie",
        order: 2,
        lessons: [
          {
            id: "lesson_002_002_001",
            title: "Hook useState",
            description: "Gérer l’état avec les Hooks React",
            duration: "24m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_002_001_001",
                type: "video",
                title: "Explications sur useState",
                url: "https://www.youtube.com/watch?v=O6P86uwfdR0",
                duration: "18m",
              },
              {
                id: "material_002_002_001_002",
                type: "code",
                title: "Exemples d’état",
                url: "https://react.dev/reference/react/useState",
              },
            ],
          },
          {
            id: "lesson_002_002_002",
            title: "Hook useEffect",
            description:
              "Effets de bord et cycle de vie dans les composants fonctionnels",
            duration: "28m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_002_002_001",
                type: "video",
                title: "Maîtrise de useEffect",
                url: "https://www.youtube.com/watch?v=0ZJgIjIuY7U",
                duration: "22m",
              },
              {
                id: "material_002_002_002_002",
                type: "exercise",
                title: "Pratique des effets",
                url: "https://react.dev/reference/react/useEffect",
              },
              {
                id: "material_002_002_002_003",
                type: "quiz",
                title: "Quiz sur les Hooks",
                url: "https://react.dev/learn/managing-state",
                questionsCount: 10,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_003",
        title: "Hooks avancés",
        description:
          "Maîtriser useContext, useReducer et les hooks personnalisés",
        order: 3,
        lessons: [
          {
            id: "lesson_002_003_001",
            title: "API Context et useContext",
            description: "Gestion d’état globale avec Context",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_003_001_001",
                type: "video",
                title: "Guide de l’API Context",
                url: "https://www.youtube.com/watch?v=5LrDIWkK_Bc",
                duration: "24m",
              },
              {
                id: "material_002_003_001_002",
                type: "document",
                title: "Schémas de Context",
                url: "https://react.dev/learn/passing-data-deeply-with-context",
              },
            ],
          },
          {
            id: "lesson_002_003_002",
            title: "useReducer pour un état complexe",
            description: "Gestion d’état type Redux avec useReducer",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_003_002_001",
                type: "video",
                title: "Tutoriel useReducer",
                url: "https://www.youtube.com/watch?v=kK_Wqx3RnHk",
                duration: "26m",
              },
              {
                id: "material_002_003_002_002",
                type: "code",
                title: "Exemples de reducers",
                url: "https://react.dev/reference/react/useReducer",
              },
            ],
          },
          {
            id: "lesson_002_003_003",
            title: "Créer des hooks personnalisés",
            description: "Créer des hooks personnalisés réutilisables",
            duration: "28m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_003_003_001",
                type: "video",
                title: "Hooks personnalisés",
                url: "https://www.youtube.com/watch?v=6ThXsUwLWvc",
                duration: "22m",
              },
              {
                id: "material_002_003_003_002",
                type: "exercise",
                title: "Construire votre propre hook",
                url: "https://react.dev/learn/reusing-logic-with-custom-hooks",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_004",
        title: "Construire des applications réelles",
        description: "Assembler le tout dans un projet complet",
        order: 4,
        lessons: [
          {
            id: "lesson_002_004_001",
            title: "Configuration et architecture du projet",
            description:
              "Structurer une application React prête pour la production",
            duration: "25m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_001_001",
                type: "video",
                title: "Architecture de l’application",
                url: "https://www.youtube.com/watch?v=NqzdVN2tyvQ",
                duration: "20m",
              },
              {
                id: "material_002_004_001_002",
                type: "code",
                title: "Modèle de démarrage",
                url: "https://vitejs.dev/guide/#scaffolding-your-first-vite-project",
              },
            ],
          },
          {
            id: "lesson_002_004_002",
            title: "Intégration d’API",
            description: "Récupérer et afficher des données d’API",
            duration: "35m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_002_001",
                type: "video",
                title: "Récupération de données",
                url: "https://www.youtube.com/watch?v=cuHDQhDhvPE",
                duration: "28m",
              },
              {
                id: "material_002_004_002_002",
                type: "exercise",
                title: "Construire un client API",
                url: "https://react.dev/learn/synchronizing-with-effects#fetching-data",
              },
            ],
          },
          {
            id: "lesson_002_004_003",
            title: "Routage avec React Router",
            description: "Naviguer entre les pages",
            duration: "30m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_003_001",
                type: "video",
                title: "Guide React Router",
                url: "https://www.youtube.com/watch?v=Ul3y1LXxzdU",
                duration: "24m",
              },
              {
                id: "material_002_004_003_002",
                type: "code",
                title: "Exemples de routage",
                url: "https://reactrouter.com/en/main/start/tutorial",
              },
            ],
          },
          {
            id: "lesson_002_004_004",
            title: "Projet final",
            description: "Créer une application Todo complète",
            duration: "45m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_004_001",
                type: "video",
                title: "Présentation du projet",
                url: "https://www.youtube.com/watch?v=hQAHSlTtcmY",
                duration: "40m",
              },
              {
                id: "material_002_004_004_002",
                type: "exercise",
                title: "Projet complet",
                url: "https://github.com/tastejs/todomvc",
              },
              {
                id: "material_002_004_004_003",
                type: "quiz",
                title: "Évaluation finale",
                url: "https://react.dev/learn/tutorial-tic-tac-toe",
                questionsCount: 15,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_005",
        title: "Performance et optimisation",
        description: "Rendre vos applications React ultra rapides",
        order: 5,
        lessons: [
          {
            id: "lesson_002_005_001",
            title: "React.memo et useMemo",
            description: "Optimiser les performances de rendu",
            duration: "26m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_005_001_001",
                type: "video",
                title: "Optimisation des performances",
                url: "https://www.youtube.com/watch?v=uojLJFt9SzY",
                duration: "20m",
              },
              {
                id: "material_002_005_001_002",
                type: "exercise",
                title: "Pratique de l’optimisation",
                url: "https://react.dev/reference/react/memo",
              },
            ],
          },
          {
            id: "lesson_002_005_002",
            title: "Découpage du code et chargement paresseux",
            description:
              "Réduire la taille du bundle et améliorer les temps de chargement",
            duration: "22m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_005_002_001",
                type: "video",
                title: "Guide de découpage du code",
                url: "https://www.youtube.com/watch?v=JU6sl_yyZqs",
                duration: "18m",
              },
              {
                id: "material_002_005_002_002",
                type: "quiz",
                title: "Quiz performance",
                url: "https://react.dev/reference/react/lazy",
                questionsCount: 8,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_003",
    title: "APIs Node.js avancées",
    subtitle:
      "Maîtriser la conception d’API REST, l’authentification, les tests et la montée en charge",
    description:
      "Plongée approfondie dans une architecture backend Node.js prête pour la production avec Express, Prisma et des tests automatisés.",
    instructor: {
      name: "Michael Thompson",
      avatar: "https://images.unsplash.com/photo-1527980965255-d3b416303d12",
    },
    thumbnail: "https://images.unsplash.com/photo-1518779578993-ec3579fee39f",
    duration: "8h 10m",
    difficulty: "Avancé",
    categories: ["Backend", "Node.js", "APIs"],
    level: 3,
    studentsEnrolled: 980,
    rating: 4.9,
    tags: ["node", "api", "express", "prisma"],
    updatedAt: "2025-08-21T12:00:00Z",
    isFree: false,
    price: { amount: 69.0, currency: "USD" },
    progress: 15,
    chapters: [
      {
        id: "chapter_003_001",
        title: "Architecture d’API",
        description: "Concevoir des API REST évolutives",
        order: 1,
        lessons: [
          {
            id: "lesson_003_001_001",
            title: "Principes de conception RESTful",
            description: "Bonnes pratiques de conception d’API",
            duration: "25m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_001_001_001",
                type: "video",
                title: "Conception d’API REST",
                url: "https://www.youtube.com/watch?v=qwfE7fSVaZM",
                duration: "20m",
              },
              {
                id: "material_003_001_001_002",
                type: "document",
                title: "Guide de conception d’API",
                url: "https://restfulapi.net/",
              },
            ],
          },
          {
            id: "lesson_003_001_002",
            title: "Schémas avancés avec Express.js",
            description: "Maîtriser les middlewares et le routage avec Express",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_001_002_001",
                type: "video",
                title: "Approfondissement d’Express",
                url: "https://www.youtube.com/watch?v=Lr9WUkeYSA8",
                duration: "28m",
              },
              {
                id: "material_003_001_002_002",
                type: "code",
                title: "Schémas avancés",
                url: "https://expressjs.com/en/guide/routing.html",
              },
            ],
          },
          {
            id: "lesson_003_001_003",
            title: "Gestion des erreurs et validation",
            description:
              "Stratégies de gestion des erreurs de niveau production",
            duration: "28m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_001_003_001",
                type: "video",
                title: "Gestion des erreurs",
                url: "https://www.youtube.com/watch?v=w2o-PL8z-K4",
                duration: "22m",
              },
              {
                id: "material_003_001_003_002",
                type: "exercise",
                title: "Pratique de la validation",
                url: "https://express-validator.github.io/docs/",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_003_002",
        title: "Authentification et sécurité",
        description:
          "Implémenter JWT, OAuth et les bonnes pratiques de sécurité",
        order: 2,
        lessons: [
          {
            id: "lesson_003_002_001",
            title: "Authentification JWT",
            description:
              "Implémenter une authentification basée sur des jetons",
            duration: "38m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_002_001_001",
                type: "video",
                title: "Implémentation JWT",
                url: "https://www.youtube.com/watch?v=mbsmsi7l3r4",
                duration: "32m",
              },
              {
                id: "material_003_002_001_002",
                type: "document",
                title: "Guide de sécurité JWT",
                url: "https://jwt.io/introduction",
              },
            ],
          },
          {
            id: "lesson_003_002_002",
            title: "Bonnes pratiques de sécurité API",
            description: "Limitation de débit, CORS et en‑têtes de sécurité",
            duration: "30m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_002_002_001",
                type: "video",
                title: "Sécurité des API",
                url: "https://www.youtube.com/watch?v=2jqok-WgelI",
                duration: "24m",
              },
              {
                id: "material_003_002_002_002",
                type: "quiz",
                title: "Quiz sécurité",
                url: "https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html",
                questionsCount: 12,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_003_003",
        title: "Base de données et Prisma",
        description: "Schémas avancés de base de données avec Prisma ORM",
        order: 3,
        lessons: [
          {
            id: "lesson_003_003_001",
            title: "Configuration de Prisma et conception de schéma",
            description: "Configurer Prisma avec PostgreSQL",
            duration: "35m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_001_001",
                type: "video",
                title: "Introduction à Prisma",
                url: "https://www.youtube.com/watch?v=RebA5J-rlwg",
                duration: "28m",
              },
              {
                id: "material_003_003_001_002",
                type: "document",
                title: "Schémas de conception",
                url: "https://www.prisma.io/docs/concepts/components/prisma-schema",
              },
            ],
          },
          {
            id: "lesson_003_003_002",
            title: "Requêtes avancées et relations",
            description: "Requêtes complexes et gestion des relations",
            duration: "40m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_002_001",
                type: "video",
                title: "Prisma avancé",
                url: "https://www.youtube.com/watch?v=CYH04BJzamo",
                duration: "34m",
              },
              {
                id: "material_003_003_002_002",
                type: "exercise",
                title: "Pratique des requêtes",
                url: "https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries",
              },
            ],
          },
          {
            id: "lesson_003_003_003",
            title: "Transactions et performance",
            description: "Optimiser les opérations de base de données",
            duration: "32m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_003_001",
                type: "video",
                title: "Optimisation de la base de données",
                url: "https://www.youtube.com/watch?v=dWYWtMqMduY",
                duration: "26m",
              },
              {
                id: "material_003_003_003_002",
                type: "document",
                title: "Guide de performance",
                url: "https://www.prisma.io/docs/guides/performance-and-optimization",
              },
            ],
          },
          {
            id: "lesson_003_003_004",
            title: "Migrations et seeding",
            description: "Gérer les changements de schéma",
            duration: "28m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_004_001",
                type: "video",
                title: "Migrations Prisma",
                url: "https://www.youtube.com/watch?v=_VPFzbtl9yM",
                duration: "22m",
              },
              {
                id: "material_003_003_004_002",
                type: "exercise",
                title: "Pratique des migrations",
                url: "https://www.prisma.io/docs/concepts/components/prisma-migrate",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_003_004",
        title: "Tests et déploiement",
        description: "Tests automatisés et déploiement en production",
        order: 4,
        lessons: [
          {
            id: "lesson_003_004_001",
            title: "Tests unitaires et d’intégration",
            description: "Tester vos API avec Jest et Supertest",
            duration: "45m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_004_001_001",
                type: "video",
                title: "Stratégies de tests",
                url: "https://www.youtube.com/watch?v=r9HdJ8P6GQI",
                duration: "38m",
              },
              {
                id: "material_003_004_001_002",
                type: "code",
                title: "Exemples de tests",
                url: "https://github.com/testjavascript/nodejs-integration-tests-best-practices",
              },
            ],
          },
          {
            id: "lesson_003_004_002",
            title: "Pipelines CI/CD",
            description: "Automatiser les tests et le déploiement",
            duration: "38m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_004_002_001",
                type: "video",
                title: "Mise en place CI/CD",
                url: "https://www.youtube.com/watch?v=scEDHsr3APg",
                duration: "32m",
              },
              {
                id: "material_003_004_002_002",
                type: "exercise",
                title: "Configuration de pipeline",
                url: "https://docs.github.com/en/actions/quickstart",
              },
            ],
          },
          {
            id: "lesson_003_004_003",
            title: "Déploiement en production",
            description: "Déployer sur des plateformes cloud",
            duration: "42m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_004_003_001",
                type: "video",
                title: "Guide de déploiement",
                url: "https://www.youtube.com/watch?v=kBKIv1fPQlE",
                duration: "35m",
              },
              {
                id: "material_003_004_003_002",
                type: "document",
                title: "Liste de contrôle de production",
                url: "https://github.com/goldbergyoni/nodebestpractices#6-going-to-production-practices",
              },
              {
                id: "material_003_004_003_003",
                type: "quiz",
                title: "Évaluation finale",
                url: "https://nodejs.org/en/docs/guides/",
                questionsCount: 20,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_005",
    title: "Fondamentaux de Docker & DevOps",
    subtitle:
      "Déployez des applications comme un pro avec Docker, CI/CD et les outils cloud",
    description:
      "Apprenez la conteneurisation, les pipelines CI/CD, les workflows de production et les bonnes pratiques de déploiement.",
    instructor: {
      name: "Alex Johnson",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    },
    thumbnail: "https://images.unsplash.com/photo-1527430253228-e93688616381",
    duration: "5h 50m",
    difficulty: "Intermédiaire",
    categories: ["DevOps", "Docker", "Cloud"],
    level: 2,
    studentsEnrolled: 2700,
    rating: 4.8,
    tags: ["docker", "ci/cd", "cloud", "devops"],
    updatedAt: "2025-10-01T12:00:00Z",
    isFree: false,
    price: { amount: 59.99, currency: "USD" },
    progress: 45,
    chapters: [
      {
        id: "chapter_005_001",
        title: "Fondamentaux de Docker",
        description: "Maîtriser la conteneurisation avec Docker",
        order: 1,
        lessons: [
          {
            id: "lesson_005_001_001",
            title: "Introduction aux conteneurs",
            description: "Comprendre les concepts de conteneurisation",
            duration: "20m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_005_001_001_001",
                type: "video",
                title: "Bases des conteneurs",
                url: "https://www.youtube.com/watch?v=pg19Z8LL06w",
                duration: "15m",
              },
              {
                id: "material_005_001_001_002",
                type: "document",
                title: "Vue d’ensemble de Docker",
                url: "https://docs.docker.com/get-started/",
              },
            ],
          },
          {
            id: "lesson_005_001_002",
            title: "Bonnes pratiques Dockerfile",
            description: "Écrire des Dockerfiles efficaces",
            duration: "28m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_005_001_002_001",
                type: "video",
                title: "Optimisation des Dockerfiles",
                url: "https://www.youtube.com/watch?v=8vXoMqWgbQQ",
                duration: "22m",
              },
              {
                id: "material_005_001_002_002",
                type: "code",
                title: "Exemples de Dockerfile",
                url: "https://docs.docker.com/develop/dev-best-practices/",
              },
            ],
          },
          {
            id: "lesson_005_001_003",
            title: "Docker Compose",
            description: "Applications multi‑conteneurs",
            duration: "32m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_001_003_001",
                type: "video",
                title: "Guide Docker Compose",
                url: "https://www.youtube.com/watch?v=Qw9zlE3t8Ko",
                duration: "26m",
              },
              {
                id: "material_005_001_003_002",
                type: "exercise",
                title: "Pratique de Compose",
                url: "https://docs.docker.com/compose/gettingstarted/",
              },
            ],
          },
          {
            id: "lesson_005_001_004",
            title: "Volumes et réseau Docker",
            description: "Persister les données et connecter les conteneurs",
            duration: "24m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_001_004_001",
                type: "video",
                title: "Volumes et réseaux",
                url: "https://www.youtube.com/watch?v=Gjnup-PuquQ",
                duration: "20m",
              },
              {
                id: "material_005_001_004_002",
                type: "code",
                title: "Exemples de réseau",
                url: "https://docs.docker.com/network/",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_005_002",
        title: "Pipelines CI/CD",
        description: "Automatiser votre flux de déploiement",
        order: 2,
        lessons: [
          {
            id: "lesson_005_002_001",
            title: "Bases de GitHub Actions",
            description: "Mettre en place des workflows automatisés",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_002_001_001",
                type: "video",
                title: "Tutoriel GitHub Actions",
                url: "https://www.youtube.com/watch?v=R8_veQiYBjI",
                duration: "24m",
              },
              {
                id: "material_005_002_001_002",
                type: "code",
                title: "Modèles de workflow",
                url: "https://github.com/sdras/awesome-actions",
              },
            ],
          },
          {
            id: "lesson_005_002_002",
            title: "Tests en CI/CD",
            description: "Pipelines de tests automatisés",
            duration: "35m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_002_002_001",
                type: "video",
                title: "Stratégies de tests CI",
                url: "https://www.youtube.com/watch?v=tMESFF5sVlU",
                duration: "28m",
              },
              {
                id: "material_005_002_002_002",
                type: "exercise",
                title: "Pipeline de build",
                url: "https://docs.github.com/en/actions/automating-builds-and-tests",
              },
            ],
          },
          {
            id: "lesson_005_002_003",
            title: "Déploiements en production",
            description:
              "Déployer sur des plateformes cloud en toute confiance",
            duration: "42m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_002_003_001",
                type: "video",
                title: "Stratégies de déploiement",
                url: "https://www.youtube.com/watch?v=eB0nUzAI7M8",
                duration: "36m",
              },
              {
                id: "material_005_002_003_002",
                type: "document",
                title: "Liste de contrôle de déploiement",
                url: "https://github.com/mtdvio/going-to-production",
              },
              {
                id: "material_005_002_003_003",
                type: "quiz",
                title: "Quiz final DevOps",
                url: "https://roadmap.sh/devops",
                questionsCount: 18,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_006",
    title: "SQL & conception de base de données",
    subtitle:
      "Maîtriser Postgres, l’indexation, la conception de schéma et des schémas de production réels",
    description:
      "Un guide complet des bases de données relationnelles, de Postgres, de l’optimisation et de l’architecture de schéma.",
    instructor: {
      name: "Nadia Hassan",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    },
    thumbnail: "https://images.unsplash.com/photo-1559526324-593bc073d938",
    duration: "6h 05m",
    difficulty: "Intermédiaire",
    categories: ["Bases de données", "SQL", "Backend"],
    level: 2,
    studentsEnrolled: 1890,
    rating: 4.7,
    tags: ["sql", "postgres", "schema"],
    updatedAt: "2025-09-15T12:00:00Z",
    isFree: false,
    price: { amount: 54.0, currency: "USD" },
    progress: 80,
    chapters: [
      {
        id: "chapter_006_001",
        title: "Fondamentaux SQL",
        description: "Maîtriser les requêtes SQL et la manipulation de données",
        order: 1,
        lessons: [
          {
            id: "lesson_006_001_001",
            title: "Requêtes SELECT et filtrage",
            description: "Écrire des instructions SELECT efficaces",
            duration: "25m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_001_001",
                type: "video",
                title: "Bases de SQL",
                url: "https://www.youtube.com/watch?v=5hzZtqCNQKk",
                duration: "20m",
              },
              {
                id: "material_006_001_001_002",
                type: "exercise",
                title: "Pratique des requêtes",
                url: "https://www.sqlteaching.com/",
              },
            ],
          },
          {
            id: "lesson_006_001_002",
            title: "JOIN et relations",
            description: "Combiner des données de plusieurs tables",
            duration: "30m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_002_001",
                type: "video",
                title: "Comprendre les JOIN",
                url: "https://www.youtube.com/watch?v=9yeOJ0ZMUYw",
                duration: "24m",
              },
              {
                id: "material_006_001_002_002",
                type: "code",
                title: "Exemples de JOIN",
                url: "https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-joins/",
              },
            ],
          },
          {
            id: "lesson_006_001_003",
            title: "Agrégations et GROUP BY",
            description: "Analyser des données avec des fonctions d’agrégation",
            duration: "28m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_003_001",
                type: "video",
                title: "Fonctions d’agrégation",
                url: "https://www.youtube.com/watch?v=tMcOMdULldg",
                duration: "22m",
              },
              {
                id: "material_006_001_003_002",
                type: "quiz",
                title: "Quiz bases de SQL",
                url: "https://www.postgresql.org/docs/current/tutorial-agg.html",
                questionsCount: 10,
              },
            ],
          },
          {
            id: "lesson_006_001_004",
            title: "Sous‑requêtes et CTE",
            description: "Techniques de requêtes avancées",
            duration: "34m",
            order: 4,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_004_001",
                type: "video",
                title: "Requêtes complexes",
                url: "https://www.youtube.com/watch?v=XQ_6G4kj_xk",
                duration: "28m",
              },
              {
                id: "material_006_001_004_002",
                type: "exercise",
                title: "Pratique des requêtes avancées",
                url: "https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-cte/",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_006_002",
        title: "Conception de base de données",
        description: "Conception de schémas et normalisation",
        order: 2,
        lessons: [
          {
            id: "lesson_006_002_001",
            title: "Principes de normalisation",
            description: "Concevoir des schémas de base de données normalisés",
            duration: "32m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_002_001_001",
                type: "video",
                title: "Normalisation de base de données",
                url: "https://www.youtube.com/watch?v=GFQaEYEc8_8",
                duration: "26m",
              },
              {
                id: "material_006_002_001_002",
                type: "document",
                title: "Guide des formes normales",
                url: "https://www.postgresql.org/docs/current/tutorial-concepts.html",
              },
            ],
          },
          {
            id: "lesson_006_002_002",
            title: "Index et performance",
            description: "Optimiser les requêtes avec un indexage approprié",
            duration: "35m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_002_002_001",
                type: "video",
                title: "Index Optimization",
                url: "https://www.youtube.com/watch?v=rKlKLkD1akI",
                duration: "28m",
              },
              {
                id: "material_006_002_002_002",
                type: "exercise",
                title: "Index Practice",
                url: "https://www.postgresqltutorial.com/postgresql-indexes/",
              },
            ],
          },
          {
            id: "lesson_006_002_003",
            title: "Views and Stored Procedures",
            description: "Encapsulate complex logic",
            duration: "29m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_002_003_001",
                type: "video",
                title: "Views and Procedures",
                url: "https://www.youtube.com/watch?v=xaWlS9HtWYw",
                duration: "24m",
              },
              {
                id: "material_006_002_003_002",
                type: "code",
                title: "Procedure Examples",
                url: "https://www.postgresql.org/docs/current/sql-createview.html",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_006_003",
        title: "Advanced PostgreSQL",
        description: "PostgreSQL-specific features",
        order: 3,
        lessons: [
          {
            id: "lesson_006_003_001",
            title: "Advanced Data Types",
            description: "JSON, arrays, and custom types",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_003_001_001",
                type: "video",
                title: "Postgres Data Types",
                url: "https://www.youtube.com/watch?v=1VVlBqYpImM",
                duration: "24m",
              },
              {
                id: "material_006_003_001_002",
                type: "code",
                title: "Type Examples",
                url: "https://www.postgresql.org/docs/current/datatype.html",
              },
            ],
          },
          {
            id: "lesson_006_003_002",
            title: "Transactions and Concurrency",
            description: "Managing concurrent database access",
            duration: "38m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_003_002_001",
                type: "video",
                title: "Transaction Management",
                url: "https://www.youtube.com/watch?v=D0L49xnJNLk",
                duration: "32m",
              },
              {
                id: "material_006_003_002_002",
                type: "quiz",
                title: "Advanced PostgreSQL Quiz",
                url: "https://www.postgresql.org/docs/current/tutorial-transactions.html",
                questionsCount: 12,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_006_004",
        title: "Production Database Management",
        description: "Manage databases at scale",
        order: 4,
        lessons: [
          {
            id: "lesson_006_004_001",
            title: "Backup and Recovery",
            description: "Protect your data",
            duration: "27m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_004_001_001",
                type: "video",
                title: "Backup Strategies",
                url: "https://www.youtube.com/watch?v=0GvMsXyGp6U",
                duration: "22m",
              },
              {
                id: "material_006_004_001_002",
                type: "document",
                title: "Recovery Procedures",
                url: "https://www.postgresql.org/docs/current/backup.html",
              },
            ],
          },
          {
            id: "lesson_006_004_002",
            title: "Monitoring and Maintenance",
            description: "Keep your database healthy",
            duration: "31m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_004_002_001",
                type: "video",
                title: "Database Monitoring",
                url: "https://www.youtube.com/watch?v=1aXk2nLVTw4",
                duration: "26m",
              },
              {
                id: "material_006_004_002_002",
                type: "exercise",
                title: "Maintenance Tasks",
                url: "https://www.postgresql.org/docs/current/maintenance.html",
              },
            ],
          },
          {
            id: "lesson_006_004_003",
            title: "Scaling Strategies",
            description: "Scale your database for growth",
            duration: "36m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_004_003_001",
                type: "video",
                title: "Database Scaling",
                url: "https://www.youtube.com/watch?v=dWL5gx_bop4",
                duration: "30m",
              },
              {
                id: "material_006_004_003_002",
                type: "quiz",
                title: "Final Database Quiz",
                url: "https://www.postgresql.org/docs/current/tutorial.html",
                questionsCount: 15,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_007",
    title: "Python pour l’analyse de données",
    subtitle:
      "Analyser des jeux de données, visualiser les résultats et produire des insights prédictifs",
    description:
      "Formation pratique avec pandas, NumPy, Matplotlib et des workflows concrets de nettoyage de données.",
    instructor: {
      name: "David Park",
      avatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91",
    },
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c",
    duration: "7h 15m",
    difficulty: "Intermédiaire",
    categories: ["Science des données", "Python"],
    level: 2,
    studentsEnrolled: 5200,
    rating: 4.9,
    tags: ["python", "data", "analysis", "pandas"],
    updatedAt: "2025-11-01T12:00:00Z",
    isFree: false,
    price: { amount: 79.0, currency: "USD" },
    progress: 50,
    chapters: [
      {
        id: "chapter_007_001",
        title: "Bases de Python et Pandas",
        description: "Se lancer dans l’analyse de données en Python",
        order: 1,
        lessons: [
          {
            id: "lesson_007_001_001",
            title: "Fondamentaux de NumPy",
            description:
              "Travailler avec des tableaux et des données numériques",
            duration: "30m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_001_001",
                type: "video",
                title: "Introduction à NumPy",
                url: "https://www.youtube.com/watch?v=QUT1VHiLmmI",
                duration: "24m",
              },
              {
                id: "material_007_001_001_002",
                type: "code",
                title: "Exemples NumPy",
                url: "https://numpy.org/doc/stable/user/quickstart.html",
              },
            ],
          },
          {
            id: "lesson_007_001_002",
            title: "DataFrames Pandas",
            description: "Manipulation de données avec Pandas",
            duration: "35m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_002_001",
                type: "video",
                title: "Bases de Pandas",
                url: "https://www.youtube.com/watch?v=vmEHCJofslg",
                duration: "28m",
              },
              {
                id: "material_007_001_002_002",
                type: "exercise",
                title: "Pratique DataFrame",
                url: "https://pandas.pydata.org/docs/user_guide/10min.html",
              },
            ],
          },
          {
            id: "lesson_007_001_003",
            title: "Techniques de nettoyage de données",
            description:
              "Gérer les données manquantes et les valeurs aberrantes",
            duration: "32m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_003_001",
                type: "video",
                title: "Nettoyage des données",
                url: "https://www.youtube.com/watch?v=KdmPHEnPJPs",
                duration: "26m",
              },
              {
                id: "material_007_001_003_002",
                type: "document",
                title: "Bonnes pratiques de nettoyage",
                url: "https://pandas.pydata.org/docs/user_guide/missing_data.html",
              },
            ],
          },
          {
            id: "lesson_007_001_004",
            title: "Transformation des données",
            description: "Restructurer et pivoter des données",
            duration: "29m",
            order: 4,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_004_001",
                type: "video",
                title: "Transformer des données",
                url: "https://www.youtube.com/watch?v=vCFjGKy5IFI",
                duration: "24m",
              },
              {
                id: "material_007_001_004_002",
                type: "exercise",
                title: "Pratique de la transformation",
                url: "https://pandas.pydata.org/docs/user_guide/reshaping.html",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_007_002",
        title: "Visualisation de données",
        description: "Créer des visualisations percutantes",
        order: 2,
        lessons: [
          {
            id: "lesson_007_002_001",
            title: "Fondamentaux de Matplotlib",
            description: "Tracé de base avec Matplotlib",
            duration: "28m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_002_001_001",
                type: "video",
                title: "Guide Matplotlib",
                url: "https://www.youtube.com/watch?v=DAQNHzOcO5A",
                duration: "22m",
              },
              {
                id: "material_007_002_001_002",
                type: "code",
                title: "Exemples de tracés",
                url: "https://matplotlib.org/stable/tutorials/introductory/pyplot.html",
              },
            ],
          },
          {
            id: "lesson_007_002_002",
            title: "Seaborn pour les graphiques statistiques",
            description: "Visualisations avancées avec Seaborn",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_002_002_001",
                type: "video",
                title: "Tutoriel Seaborn",
                url: "https://www.youtube.com/watch?v=6GUZXDef2U0",
                duration: "26m",
              },
              {
                id: "material_007_002_002_002",
                type: "exercise",
                title: "Projet de visualisation",
                url: "https://seaborn.pydata.org/tutorial.html",
              },
            ],
          },
          {
            id: "lesson_007_002_003",
            title: "Visualisations interactives",
            description: "Créer des graphiques interactifs avec Plotly",
            duration: "27m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_002_003_001",
                type: "video",
                title: "Tutoriel Plotly",
                url: "https://www.youtube.com/watch?v=hSPmj7mK6ng",
                duration: "22m",
              },
              {
                id: "material_007_002_003_002",
                type: "code",
                title: "Exemples interactifs",
                url: "https://plotly.com/python/getting-started/",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_007_003",
        title: "Projets concrets",
        description: "Appliquer vos compétences à des jeux de données réels",
        order: 3,
        lessons: [
          {
            id: "lesson_007_003_001",
            title: "Projet d’analyse exploratoire",
            description: "Analyser un jeu de données complet",
            duration: "50m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_003_001_001",
                type: "video",
                title: "Présentation EDA",
                url: "https://www.youtube.com/watch?v=_wNowdG0slc",
                duration: "42m",
              },
              {
                id: "material_007_003_001_002",
                type: "exercise",
                title: "Analyse complète",
                url: "https://www.kaggle.com/learn/data-visualization",
              },
            ],
          },
          {
            id: "lesson_007_003_002",
            title: "Bases de la modélisation prédictive",
            description: "Construire votre premier modèle prédictif",
            duration: "45m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_003_002_001",
                type: "video",
                title: "Introduction à la modélisation",
                url: "https://www.youtube.com/watch?v=7eh4d6sabA0",
                duration: "38m",
              },
              {
                id: "material_007_003_002_002",
                type: "quiz",
                title: "Évaluation finale",
                url: "https://scikit-learn.org/stable/tutorial/basic/tutorial.html",
                questionsCount: 18,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_008",
    title: "Branding & marketing pour startups",
    subtitle: "Construire une identité de marque qui se vend vraiment",
    description:
      "Apprenez le positionnement, le design de marque, la stratégie de contenu, le storytelling et la stack marketing moderne.",
    instructor: {
      name: "Laura Smith",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    },
    thumbnail: "https://images.unsplash.com/photo-1492724441997-5dc865305da7",
    duration: "2h 50m",
    difficulty: "Débutant",
    categories: ["Marketing", "Branding"],
    level: 1,
    studentsEnrolled: 3100,
    rating: 4.5,
    tags: ["branding", "marketing", "storytelling"],
    updatedAt: "2025-08-10T12:00:00Z",
    isFree: true,
    price: null,
    progress: 90,
    chapters: [
      {
        id: "chapter_008_001",
        title: "Fondations de la marque",
        description: "Construire une identité de marque solide",
        order: 1,
        lessons: [
          {
            id: "lesson_008_001_001",
            title: "Trouver votre positionnement de marque",
            description: "Définir votre positionnement unique sur le marché",
            duration: "22m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_001_001",
                type: "video",
                title: "Positionnement de marque",
                url: "https://www.youtube.com/watch?v=iHuDlB7tDhM",
                duration: "18m",
              },
              {
                id: "material_008_001_001_002",
                type: "document",
                title: "Fiche de positionnement",
                url: "https://www.strategyzer.com/canvas/value-proposition-canvas",
              },
            ],
          },
          {
            id: "lesson_008_001_002",
            title: "Construire votre histoire de marque",
            description: "Storytelling pour startups",
            duration: "20m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_002_001",
                type: "video",
                title: "Storytelling de marque",
                url: "https://www.youtube.com/watch?v=yPvuhJZ0ftU",
                duration: "16m",
              },
              {
                id: "material_008_001_002_002",
                type: "exercise",
                title: "Cadre narratif",
                url: "https://www.storybrands.com/",
              },
            ],
          },
          {
            id: "lesson_008_001_003",
            title: "Conception d’identité visuelle",
            description: "Créer une identité visuelle mémorable",
            duration: "25m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_003_001",
                type: "video",
                title: "Fondamentaux du design",
                url: "https://www.youtube.com/watch?v=RBq4E_HAw8Y",
                duration: "20m",
              },
              {
                id: "material_008_001_003_002",
                type: "document",
                title: "Guides de conception",
                url: "https://www.canva.com/learn/brand-identity/",
              },
            ],
          },
          {
            id: "lesson_008_001_004",
            title: "Voix et message de marque",
            description: "Développer votre voix de marque unique",
            duration: "21m",
            order: 4,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_004_001",
                type: "video",
                title: "Voix et ton",
                url: "https://www.youtube.com/watch?v=XWu8f8khMFY",
                duration: "16m",
              },
              {
                id: "material_008_001_004_002",
                type: "exercise",
                title: "Atelier voix de marque",
                url: "https://mailchimp.com/resources/brand-voice/",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_008_002",
        title: "Stratégie de contenu",
        description: "Créer du contenu qui convertit",
        order: 2,
        lessons: [
          {
            id: "lesson_008_002_001",
            title: "Fondamentaux du content marketing",
            description: "Construire une stratégie de contenu",
            duration: "24m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_002_001_001",
                type: "video",
                title: "Stratégie de contenu",
                url: "https://www.youtube.com/watch?v=S3HhGxuEhWw",
                duration: "20m",
              },
              {
                id: "material_008_002_001_002",
                type: "exercise",
                title: "Calendrier de contenu",
                url: "https://contentmarketinginstitute.com/content-marketing-strategy/",
              },
            ],
          },
          {
            id: "lesson_008_002_002",
            title: "Marketing des réseaux sociaux",
            description:
              "Développer votre audience sur les plateformes sociales",
            duration: "26m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_002_002_001",
                type: "video",
                title: "Guide réseaux sociaux",
                url: "https://www.youtube.com/watch?v=jHTuJ1q2xFU",
                duration: "22m",
              },
              {
                id: "material_008_002_002_002",
                type: "quiz",
                title: "Quiz marketing",
                url: "https://www.hubspot.com/marketing-statistics",
                questionsCount: 8,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_008_003",
        title: "Croissance et analytique",
        description: "Mesurer et optimiser votre marketing",
        order: 3,
        lessons: [
          {
            id: "lesson_008_003_001",
            title: "Analytique marketing",
            description: "Suivre et mesurer la performance marketing",
            duration: "20m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_008_003_001_001",
                type: "video",
                title: "Bases de l’analytique",
                url: "https://www.youtube.com/watch?v=T3HKBpAU9lk",
                duration: "16m",
              },
              {
                id: "material_008_003_001_002",
                type: "document",
                title: "Guide des métriques",
                url: "https://analytics.google.com/analytics/academy/",
              },
            ],
          },
          {
            id: "lesson_008_003_002",
            title: "Stratégies de growth hacking",
            description: "Passer à l’échelle votre marketing startup",
            duration: "22m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_008_003_002_001",
                type: "video",
                title: "Tactiques de croissance",
                url: "https://www.youtube.com/watch?v=N8qGUFxfG2g",
                duration: "18m",
              },
              {
                id: "material_008_003_002_002",
                type: "quiz",
                title: "Quiz marketing final",
                url: "https://www.growthhackers.com/",
                questionsCount: 10,
              },
            ],
          },
        ],
      },
    ],
  },
] as const;

export const quizObject = {
  id: "quiz_001",
  title: "Évaluation des fondamentaux de React",
  description:
    "Testez vos connaissances des bases de React, des hooks et des modèles de composants",
  duration: "30m",
  totalQuestions: 8,
  passingScore: 70,
  questions: [
    {
      id: "q1",
      type: "multiple-choice",
      question:
        "Quelle est la bonne manière de mettre à jour l’état dans un composant fonctionnel ?",
      points: 10,
      options: [
        { id: "a", text: "this.setState({ count: 1 })", isCorrect: false },
        { id: "b", text: "setState({ count: 1 })", isCorrect: false },
        { id: "c", text: "setCount(1)", isCorrect: true },
        { id: "d", text: "updateState(count, 1)", isCorrect: false },
      ],
      explanation:
        "Dans les composants fonctionnels, on utilise la fonction de mise à jour retournée par le hook useState (par ex. setCount) pour mettre à jour l’état.",
    },
    {
      id: "q2",
      type: "true-false",
      question:
        "Les composants React doivent toujours retourner un seul élément racine ou un fragment.",
      points: 5,
      correctAnswer: true,
      explanation:
        "Les composants React doivent retourner un seul élément racine. Vous pouvez utiliser des fragments (<></>) pour éviter d’ajouter des nœuds DOM supplémentaires.",
    },
    {
      id: "q3",
      type: "multiple-choice",
      question:
        "Quel hook devez‑vous utiliser pour gérer des effets de bord dans un composant fonctionnel ?",
      points: 10,
      options: [
        { id: "a", text: "useState", isCorrect: false },
        { id: "b", text: "useEffect", isCorrect: true },
        { id: "c", text: "useContext", isCorrect: false },
        { id: "d", text: "useReducer", isCorrect: false },
      ],
      explanation:
        "useEffect est le hook destiné à gérer les effets de bord comme la récupération de données, les abonnements ou la manipulation du DOM.",
    },
    {
      id: "q4",
      type: "multiple-select",
      question:
        "Lesquelles des options suivantes sont des façons valides de transmettre des données dans React ? (Sélectionnez toutes les réponses valides)",
      points: 15,
      options: [
        { id: "a", text: "Props du parent vers l’enfant", isCorrect: true },
        { id: "b", text: "API Context", isCorrect: true },
        { id: "c", text: "Mutation directe de l’état", isCorrect: false },
        { id: "d", text: "Fonctions de rappel (callbacks)", isCorrect: true },
        { id: "e", text: "Variables globales", isCorrect: false },
      ],
      explanation:
        "Les données peuvent être transmises via les props, l’API Context et les fonctions de rappel. La mutation directe de l’état et les variables globales sont des anti‑patterns en React.",
    },
    {
      id: "q5",
      type: "code-completion",
      question:
        "Complétez le hook useState pour gérer un compteur initialisé à 0 :",
      points: 15,
      code: "const [count, setCount] = ______(0);",
      correctAnswer: "useState",
      alternatives: ["React.useState"],
      explanation:
        "Le hook useState permet d’ajouter un état aux composants fonctionnels. Il prend la valeur initiale de l’état en argument.",
    },
    {
      id: "q6",
      type: "ordering",
      question:
        "Classez les phases du cycle de vie d’un composant React dans l’ordre correct :",
      points: 15,
      items: [
        { id: "1", text: "Montage (Mounting)", correctOrder: 1 },
        { id: "2", text: "Mise à jour (Updating)", correctOrder: 2 },
        { id: "3", text: "Démontage (Unmounting)", correctOrder: 3 },
      ],
      explanation:
        "Les composants React passent par trois phases principales : Montage (premier rendu), Mise à jour (rendus successifs) et Démontage (nettoyage).",
    },
    {
      id: "q7",
      type: "matching",
      question: "Associez chaque hook React à son usage principal :",
      points: 20,
      pairs: [
        { id: "1", left: "useState", right: "Gestion de l’état du composant" },
        { id: "2", left: "useEffect", right: "Gestion des effets de bord" },
        { id: "3", left: "useContext", right: "Accès aux valeurs de contexte" },
        { id: "4", left: "useMemo", right: "Mémoïsation de valeurs calculées" },
      ],
      explanation:
        "Chaque hook React a un rôle spécifique pour gérer différents aspects du comportement et de l’optimisation des composants.",
    },
    {
      id: "q8",
      type: "short-answer",
      question:
        "À quoi sert le tableau de dépendances dans useEffect ? (Répondez en 1–2 phrases)",
      points: 10,
      sampleAnswer:
        "Le tableau de dépendances contrôle quand l’effet s’exécute. L’effet ne se relance que lorsqu’une des dépendances change entre deux rendus.",
      keywords: ["dependency", "dependencies", "changes", "re-run", "control"],
      explanation:
        "Le tableau de dépendances est le deuxième argument de useEffect et détermine quand l’effet doit se ré‑exécuter en fonction des changements de valeurs.",
    },
  ],
} as const;
