export const courses = [
  {
    id: "course_001",
    title: "Introduction to Golang",
    subtitle: "Learn the fundamentals of Go by building real projects",
    description:
      "A beginner-friendly course teaching core Go concepts including syntax, concurrency, and building simple APIs.",
    instructor: {
      name: "John Doe",
      avatar: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    },
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    duration: "6h 30m",
    difficulty: "Beginner",
    categories: ["Programming", "Backend Development", "Golang"],
    level: 1,
    studentsEnrolled: 1275,
    rating: 4.8,
    tags: ["go", "backend", "api", "concurrency"],
    updatedAt: "2025-10-10T12:00:00Z",
    isFree: false,
    price: { amount: 49.99, currency: "USD" },
    progress: 65,
    chapters: [
      {
        id: "chapter_001_001",
        title: "Getting Started with Go",
        description: "Introduction to Go syntax and basic concepts",
        order: 1,
        lessons: [
          {
            completed: true,
            id: "lesson_001_001_001",
            title: "Installing Go and Setting Up Your Environment",
            description:
              "Learn how to install Go and configure your development environment",
            duration: "12m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_001_001_001_001",
                type: "video",
                title: "Installation Guide",
                url: "https://example.com/video1",
                duration: "8m",
              },
              {
                id: "material_001_001_001_002",
                type: "document",
                title: "Setup Checklist",
                url: "https://example.com/doc1",
              },
              {
                id: "material_001_001_001_003",
                type: "quiz",
                title: "Environment Setup Quiz",
                url: "https://example.com/quiz1",
                questionsCount: 5,
              },
            ],
          },
          {
            id: "lesson_001_001_002",
            title: "Your First Go Program",
            description: "Write and run your first Hello World program in Go",
            duration: "15m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_001_001_002_001",
                type: "video",
                title: "Hello World Tutorial",
                url: "https://example.com/video2",
                duration: "10m",
              },
              {
                id: "material_001_001_002_002",
                type: "code",
                title: "Starter Code",
                url: "https://example.com/code1",
              },
              {
                id: "material_001_001_002_003",
                type: "exercise",
                title: "Practice Exercise: Variables",
                url: "https://example.com/exercise1",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_002",
        title: "Go Fundamentals",
        description: "Deep dive into Go's core features",
        order: 2,
        lessons: [
          {
            id: "lesson_001_002_001",
            title: "Variables and Data Types",
            description: "Understanding Go's type system",
            duration: "20m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_001_001",
                type: "video",
                title: "Data Types Explained",
                url: "https://example.com/video3",
                duration: "15m",
              },
              {
                id: "material_001_002_001_002",
                type: "document",
                title: "Type System Reference",
                url: "https://example.com/doc2",
              },
            ],
          },
          {
            id: "lesson_001_002_002",
            title: "Control Structures",
            description: "Learn if-else, loops, and switch statements in Go",
            duration: "25m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_002_001",
                type: "video",
                title: "Control Flow in Go",
                url: "https://example.com/video6",
                duration: "18m",
              },
              {
                id: "material_001_002_002_002",
                type: "exercise",
                title: "Loop Exercises",
                url: "https://example.com/exercise2",
              },
            ],
          },
          {
            id: "lesson_001_002_003",
            title: "Functions and Methods",
            description: "Master functions, methods, and receivers",
            duration: "30m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_003_001",
                type: "video",
                title: "Functions Deep Dive",
                url: "https://example.com/video7",
                duration: "22m",
              },
              {
                id: "material_001_002_003_002",
                type: "code",
                title: "Method Examples",
                url: "https://example.com/code2",
              },
            ],
          },
          {
            id: "lesson_001_002_004",
            title: "Structs and Pointers",
            description: "Working with structs and pointer mechanics",
            duration: "27m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_002_004_001",
                type: "video",
                title: "Structs Explained",
                url: "https://example.com/video65",
                duration: "20m",
              },
              {
                id: "material_001_002_004_002",
                type: "exercise",
                title: "Struct Practice",
                url: "https://example.com/exercise22",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_003",
        title: "Advanced Go Concepts",
        description: "Master concurrency, interfaces, and error handling",
        order: 3,
        lessons: [
          {
            id: "lesson_001_003_001",
            title: "Goroutines and Channels",
            description: "Understanding Go's concurrency model",
            duration: "35m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_003_001_001",
                type: "video",
                title: "Concurrency Fundamentals",
                url: "https://example.com/video8",
                duration: "28m",
              },
              {
                id: "material_001_003_001_002",
                type: "exercise",
                title: "Goroutine Practice",
                url: "https://example.com/exercise3",
              },
            ],
          },
          {
            id: "lesson_001_003_002",
            title: "Interfaces and Type Assertions",
            description: "Polymorphism in Go",
            duration: "28m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_003_002_001",
                type: "video",
                title: "Understanding Interfaces",
                url: "https://example.com/video9",
                duration: "20m",
              },
              {
                id: "material_001_003_002_002",
                type: "document",
                title: "Interface Patterns",
                url: "https://example.com/doc3",
              },
            ],
          },
          {
            id: "lesson_001_003_003",
            title: "Error Handling Best Practices",
            description: "Proper error handling in Go applications",
            duration: "22m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_003_003_001",
                type: "video",
                title: "Error Handling Patterns",
                url: "https://example.com/video10",
                duration: "18m",
              },
              {
                id: "material_001_003_003_002",
                type: "quiz",
                title: "Error Handling Quiz",
                url: "https://example.com/quiz2",
                questionsCount: 8,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_004",
        title: "Building REST APIs",
        description: "Create production-ready APIs with Go",
        order: 4,
        lessons: [
          {
            id: "lesson_001_004_001",
            title: "HTTP Server Basics",
            description: "Building your first HTTP server",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_004_001_001",
                type: "video",
                title: "HTTP Server Setup",
                url: "https://example.com/video11",
                duration: "25m",
              },
              {
                id: "material_001_004_001_002",
                type: "code",
                title: "Server Starter Template",
                url: "https://example.com/code3",
              },
            ],
          },
          {
            id: "lesson_001_004_002",
            title: "Routing and Middleware",
            description: "Implement routing patterns and middleware",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_004_002_001",
                type: "video",
                title: "Routing with Gorilla Mux",
                url: "https://example.com/video12",
                duration: "26m",
              },
              {
                id: "material_001_004_002_002",
                type: "exercise",
                title: "Build a REST API",
                url: "https://example.com/exercise4",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_001_005",
        title: "Testing and Best Practices",
        description: "Write tests and follow Go conventions",
        order: 5,
        lessons: [
          {
            id: "lesson_001_005_001",
            title: "Writing Unit Tests",
            description: "Test your Go code effectively",
            duration: "33m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_005_001_001",
                type: "video",
                title: "Testing in Go",
                url: "https://example.com/video66",
                duration: "26m",
              },
              {
                id: "material_001_005_001_002",
                type: "code",
                title: "Test Examples",
                url: "https://example.com/code20",
              },
            ],
          },
          {
            id: "lesson_001_005_002",
            title: "Final Project",
            description: "Build a complete REST API with database",
            duration: "55m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_001_005_002_001",
                type: "video",
                title: "Project Walkthrough",
                url: "https://example.com/video67",
                duration: "48m",
              },
              {
                id: "material_001_005_002_002",
                type: "exercise",
                title: "Complete API Project",
                url: "https://example.com/exercise23",
              },
              {
                id: "material_001_005_002_003",
                type: "quiz",
                title: "Final Assessment",
                url: "https://example.com/quiz15",
                questionsCount: 20,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_002",
    title: "React for Beginners",
    subtitle: "Build dynamic frontends with modern React and Hooks",
    description:
      "Learn how to build scalable frontends using React, Hooks, Context API, and reusable components.",
    instructor: {
      name: "Emily Carter",
      avatar: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39",
    },
    thumbnail: "https://images.unsplash.com/photo-1587620962725-abab7fe55159",
    duration: "4h 45m",
    difficulty: "Beginner",
    categories: ["Frontend", "JavaScript", "React"],
    level: 1,
    studentsEnrolled: 3400,
    rating: 4.7,
    tags: ["react", "frontend", "hooks"],
    updatedAt: "2025-09-18T12:00:00Z",
    isFree: true,
    price: null,
    progress: 30,
    chapters: [
      {
        id: "chapter_002_001",
        title: "React Basics",
        description: "Introduction to React components and JSX",
        order: 1,
        lessons: [
          {
            id: "lesson_002_001_001",
            title: "What is React?",
            description: "Understanding React and its ecosystem",
            duration: "18m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_002_001_001_001",
                type: "video",
                title: "React Introduction",
                url: "https://example.com/video4",
                duration: "12m",
              },
              {
                id: "material_002_001_001_002",
                type: "document",
                title: "React Overview",
                url: "https://example.com/doc3",
              },
              {
                id: "material_002_001_001_003",
                type: "link",
                title: "Official React Docs",
                url: "https://react.dev",
              },
            ],
          },
          {
            id: "lesson_002_001_002",
            title: "JSX Fundamentals",
            description: "Learn JSX syntax and best practices",
            duration: "22m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_002_001_002_001",
                type: "video",
                title: "JSX Deep Dive",
                url: "https://example.com/video14",
                duration: "16m",
              },
              {
                id: "material_002_001_002_002",
                type: "code",
                title: "JSX Examples",
                url: "https://example.com/code4",
              },
            ],
          },
          {
            id: "lesson_002_001_003",
            title: "Components and Props",
            description: "Build reusable components with props",
            duration: "26m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_001_003_001",
                type: "video",
                title: "Component Composition",
                url: "https://example.com/video15",
                duration: "20m",
              },
              {
                id: "material_002_001_003_002",
                type: "exercise",
                title: "Build Components",
                url: "https://example.com/exercise5",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_002",
        title: "State and Lifecycle",
        description: "Managing component state and lifecycle methods",
        order: 2,
        lessons: [
          {
            id: "lesson_002_002_001",
            title: "useState Hook",
            description: "Managing state with React Hooks",
            duration: "24m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_002_001_001",
                type: "video",
                title: "useState Explained",
                url: "https://example.com/video16",
                duration: "18m",
              },
              {
                id: "material_002_002_001_002",
                type: "code",
                title: "State Examples",
                url: "https://example.com/code5",
              },
            ],
          },
          {
            id: "lesson_002_002_002",
            title: "useEffect Hook",
            description: "Side effects and lifecycle in functional components",
            duration: "28m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_002_002_001",
                type: "video",
                title: "useEffect Mastery",
                url: "https://example.com/video17",
                duration: "22m",
              },
              {
                id: "material_002_002_002_002",
                type: "exercise",
                title: "Effect Practice",
                url: "https://example.com/exercise6",
              },
              {
                id: "material_002_002_002_003",
                type: "quiz",
                title: "Hooks Quiz",
                url: "https://example.com/quiz4",
                questionsCount: 10,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_003",
        title: "Advanced Hooks",
        description: "Master useContext, useReducer, and custom hooks",
        order: 3,
        lessons: [
          {
            id: "lesson_002_003_001",
            title: "Context API and useContext",
            description: "Global state management with Context",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_003_001_001",
                type: "video",
                title: "Context API Guide",
                url: "https://example.com/video18",
                duration: "24m",
              },
              {
                id: "material_002_003_001_002",
                type: "document",
                title: "Context Patterns",
                url: "https://example.com/doc5",
              },
            ],
          },
          {
            id: "lesson_002_003_002",
            title: "useReducer for Complex State",
            description: "Redux-like state management with useReducer",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_003_002_001",
                type: "video",
                title: "useReducer Tutorial",
                url: "https://example.com/video19",
                duration: "26m",
              },
              {
                id: "material_002_003_002_002",
                type: "code",
                title: "Reducer Examples",
                url: "https://example.com/code6",
              },
            ],
          },
          {
            id: "lesson_002_003_003",
            title: "Building Custom Hooks",
            description: "Create reusable custom hooks",
            duration: "28m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_003_003_001",
                type: "video",
                title: "Custom Hooks",
                url: "https://example.com/video20",
                duration: "22m",
              },
              {
                id: "material_002_003_003_002",
                type: "exercise",
                title: "Build Your Own Hook",
                url: "https://example.com/exercise7",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_004",
        title: "Building Real Applications",
        description: "Put it all together in a complete project",
        order: 4,
        lessons: [
          {
            id: "lesson_002_004_001",
            title: "Project Setup and Architecture",
            description: "Structure a production React app",
            duration: "25m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_001_001",
                type: "video",
                title: "App Architecture",
                url: "https://example.com/video21",
                duration: "20m",
              },
              {
                id: "material_002_004_001_002",
                type: "code",
                title: "Starter Template",
                url: "https://example.com/code7",
              },
            ],
          },
          {
            id: "lesson_002_004_002",
            title: "API Integration",
            description: "Fetch and display data from APIs",
            duration: "35m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_002_001",
                type: "video",
                title: "Data Fetching",
                url: "https://example.com/video22",
                duration: "28m",
              },
              {
                id: "material_002_004_002_002",
                type: "exercise",
                title: "Build API Client",
                url: "https://example.com/exercise8",
              },
            ],
          },
          {
            id: "lesson_002_004_003",
            title: "Routing with React Router",
            description: "Navigate between pages",
            duration: "30m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_003_001",
                type: "video",
                title: "React Router Guide",
                url: "https://example.com/video68",
                duration: "24m",
              },
              {
                id: "material_002_004_003_002",
                type: "code",
                title: "Routing Examples",
                url: "https://example.com/code21",
              },
            ],
          },
          {
            id: "lesson_002_004_004",
            title: "Final Project",
            description: "Build a complete Todo application",
            duration: "45m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_004_004_001",
                type: "video",
                title: "Project Walkthrough",
                url: "https://example.com/video23",
                duration: "40m",
              },
              {
                id: "material_002_004_004_002",
                type: "exercise",
                title: "Complete Project",
                url: "https://example.com/exercise9",
              },
              {
                id: "material_002_004_004_003",
                type: "quiz",
                title: "Final Assessment",
                url: "https://example.com/quiz5",
                questionsCount: 15,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_002_005",
        title: "Performance and Optimization",
        description: "Make your React apps blazing fast",
        order: 5,
        lessons: [
          {
            id: "lesson_002_005_001",
            title: "React.memo and useMemo",
            description: "Optimize rendering performance",
            duration: "26m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_005_001_001",
                type: "video",
                title: "Performance Optimization",
                url: "https://example.com/video69",
                duration: "20m",
              },
              {
                id: "material_002_005_001_002",
                type: "exercise",
                title: "Optimization Practice",
                url: "https://example.com/exercise24",
              },
            ],
          },
          {
            id: "lesson_002_005_002",
            title: "Code Splitting and Lazy Loading",
            description: "Reduce bundle size and improve load times",
            duration: "22m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_002_005_002_001",
                type: "video",
                title: "Code Splitting Guide",
                url: "https://example.com/video70",
                duration: "18m",
              },
              {
                id: "material_002_005_002_002",
                type: "quiz",
                title: "Performance Quiz",
                url: "https://example.com/quiz16",
                questionsCount: 8,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_003",
    title: "Advanced Node.js APIs",
    subtitle: "Master REST API design, authentication, testing, and scaling",
    description:
      "A deep dive into production-ready Node.js backend architecture using Express, Prisma, and automated testing.",
    instructor: {
      name: "Michael Thompson",
      avatar: "https://images.unsplash.com/photo-1527980965255-d3b416303d12",
    },
    thumbnail: "https://images.unsplash.com/photo-1518779578993-ec3579fee39f",
    duration: "8h 10m",
    difficulty: "Advanced",
    categories: ["Backend", "Node.js", "APIs"],
    level: 3,
    studentsEnrolled: 980,
    rating: 4.9,
    tags: ["node", "api", "express", "prisma"],
    updatedAt: "2025-08-21T12:00:00Z",
    isFree: false,
    price: { amount: 69.0, currency: "USD" },
    progress: 15,
    chapters: [
      {
        id: "chapter_003_001",
        title: "API Architecture",
        description: "Designing scalable REST APIs",
        order: 1,
        lessons: [
          {
            id: "lesson_003_001_001",
            title: "RESTful Design Principles",
            description: "Best practices for API design",
            duration: "25m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_001_001_001",
                type: "video",
                title: "REST API Design",
                url: "https://example.com/video5",
                duration: "20m",
              },
              {
                id: "material_003_001_001_002",
                type: "document",
                title: "API Design Guide",
                url: "https://example.com/doc4",
              },
            ],
          },
          {
            id: "lesson_003_001_002",
            title: "Express.js Advanced Patterns",
            description: "Mastering Express middleware and routing",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_001_002_001",
                type: "video",
                title: "Express Deep Dive",
                url: "https://example.com/video24",
                duration: "28m",
              },
              {
                id: "material_003_001_002_002",
                type: "code",
                title: "Advanced Patterns",
                url: "https://example.com/code8",
              },
            ],
          },
          {
            id: "lesson_003_001_003",
            title: "Error Handling and Validation",
            description: "Production-grade error handling strategies",
            duration: "28m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_001_003_001",
                type: "video",
                title: "Error Handling",
                url: "https://example.com/video25",
                duration: "22m",
              },
              {
                id: "material_003_001_003_002",
                type: "exercise",
                title: "Validation Practice",
                url: "https://example.com/exercise10",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_003_002",
        title: "Authentication and Security",
        description: "Implement JWT, OAuth, and security best practices",
        order: 2,
        lessons: [
          {
            id: "lesson_003_002_001",
            title: "JWT Authentication",
            description: "Implement token-based authentication",
            duration: "38m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_002_001_001",
                type: "video",
                title: "JWT Implementation",
                url: "https://example.com/video26",
                duration: "32m",
              },
              {
                id: "material_003_002_001_002",
                type: "document",
                title: "JWT Security Guide",
                url: "https://example.com/doc6",
              },
            ],
          },
          {
            id: "lesson_003_002_002",
            title: "API Security Best Practices",
            description: "Rate limiting, CORS, and security headers",
            duration: "30m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_002_002_001",
                type: "video",
                title: "API Security",
                url: "https://example.com/video28",
                duration: "24m",
              },
              {
                id: "material_003_002_002_002",
                type: "quiz",
                title: "Security Quiz",
                url: "https://example.com/quiz6",
                questionsCount: 12,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_003_003",
        title: "Database and Prisma",
        description: "Advanced database patterns with Prisma ORM",
        order: 3,
        lessons: [
          {
            id: "lesson_003_003_001",
            title: "Prisma Setup and Schema Design",
            description: "Setting up Prisma with PostgreSQL",
            duration: "35m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_001_001",
                type: "video",
                title: "Prisma Introduction",
                url: "https://example.com/video29",
                duration: "28m",
              },
              {
                id: "material_003_003_001_002",
                type: "document",
                title: "Schema Design Patterns",
                url: "https://example.com/doc7",
              },
            ],
          },
          {
            id: "lesson_003_003_002",
            title: "Advanced Queries and Relations",
            description: "Complex queries and relationship handling",
            duration: "40m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_002_001",
                type: "video",
                title: "Advanced Prisma",
                url: "https://example.com/video30",
                duration: "34m",
              },
              {
                id: "material_003_003_002_002",
                type: "exercise",
                title: "Query Practice",
                url: "https://example.com/exercise11",
              },
            ],
          },
          {
            id: "lesson_003_003_003",
            title: "Transactions and Performance",
            description: "Optimize database operations",
            duration: "32m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_003_001",
                type: "video",
                title: "Database Optimization",
                url: "https://example.com/video31",
                duration: "26m",
              },
              {
                id: "material_003_003_003_002",
                type: "document",
                title: "Performance Guide",
                url: "https://example.com/doc8",
              },
            ],
          },
          {
            id: "lesson_003_003_004",
            title: "Migrations and Seeding",
            description: "Manage database schema changes",
            duration: "28m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_003_004_001",
                type: "video",
                title: "Prisma Migrations",
                url: "https://example.com/video71",
                duration: "22m",
              },
              {
                id: "material_003_003_004_002",
                type: "exercise",
                title: "Migration Practice",
                url: "https://example.com/exercise25",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_003_004",
        title: "Testing and Deployment",
        description: "Automated testing and production deployment",
        order: 4,
        lessons: [
          {
            id: "lesson_003_004_001",
            title: "Unit and Integration Testing",
            description: "Test your APIs with Jest and Supertest",
            duration: "45m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_004_001_001",
                type: "video",
                title: "Testing Strategies",
                url: "https://example.com/video32",
                duration: "38m",
              },
              {
                id: "material_003_004_001_002",
                type: "code",
                title: "Test Examples",
                url: "https://example.com/code10",
              },
            ],
          },
          {
            id: "lesson_003_004_002",
            title: "CI/CD Pipelines",
            description: "Automate testing and deployment",
            duration: "38m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_004_002_001",
                type: "video",
                title: "CI/CD Setup",
                url: "https://example.com/video33",
                duration: "32m",
              },
              {
                id: "material_003_004_002_002",
                type: "exercise",
                title: "Pipeline Configuration",
                url: "https://example.com/exercise12",
              },
            ],
          },
          {
            id: "lesson_003_004_003",
            title: "Production Deployment",
            description: "Deploy to cloud platforms",
            duration: "42m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_003_004_003_001",
                type: "video",
                title: "Deployment Guide",
                url: "https://example.com/video34",
                duration: "35m",
              },
              {
                id: "material_003_004_003_002",
                type: "document",
                title: "Production Checklist",
                url: "https://example.com/doc9",
              },
              {
                id: "material_003_004_003_003",
                type: "quiz",
                title: "Final Assessment",
                url: "https://example.com/quiz7",
                questionsCount: 20,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_005",
    title: "Docker & DevOps Fundamentals",
    subtitle:
      "Deploy applications like a pro using Docker, CI/CD, and cloud tooling",
    description:
      "Learn containerization, CI/CD pipelines, production workflows, and deployment best practices.",
    instructor: {
      name: "Alex Johnson",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    },
    thumbnail: "https://images.unsplash.com/photo-1527430253228-e93688616381",
    duration: "5h 50m",
    difficulty: "Intermediate",
    categories: ["DevOps", "Docker", "Cloud"],
    level: 2,
    studentsEnrolled: 2700,
    rating: 4.8,
    tags: ["docker", "ci/cd", "cloud", "devops"],
    updatedAt: "2025-10-01T12:00:00Z",
    isFree: false,
    price: { amount: 59.99, currency: "USD" },
    progress: 45,
    chapters: [
      {
        id: "chapter_005_001",
        title: "Docker Fundamentals",
        description: "Master containerization with Docker",
        order: 1,
        lessons: [
          {
            id: "lesson_005_001_001",
            title: "Introduction to Containers",
            description: "Understanding containerization concepts",
            duration: "20m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_005_001_001_001",
                type: "video",
                title: "Container Basics",
                url: "https://example.com/video35",
                duration: "15m",
              },
              {
                id: "material_005_001_001_002",
                type: "document",
                title: "Docker Overview",
                url: "https://example.com/doc10",
              },
            ],
          },
          {
            id: "lesson_005_001_002",
            title: "Dockerfile Best Practices",
            description: "Write efficient Dockerfiles",
            duration: "28m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_005_001_002_001",
                type: "video",
                title: "Dockerfile Optimization",
                url: "https://example.com/video36",
                duration: "22m",
              },
              {
                id: "material_005_001_002_002",
                type: "code",
                title: "Dockerfile Examples",
                url: "https://example.com/code11",
              },
            ],
          },
          {
            id: "lesson_005_001_003",
            title: "Docker Compose",
            description: "Multi-container applications",
            duration: "32m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_001_003_001",
                type: "video",
                title: "Docker Compose Guide",
                url: "https://example.com/video37",
                duration: "26m",
              },
              {
                id: "material_005_001_003_002",
                type: "exercise",
                title: "Compose Practice",
                url: "https://example.com/exercise13",
              },
            ],
          },
          {
            id: "lesson_005_001_004",
            title: "Docker Volumes and Networking",
            description: "Persist data and connect containers",
            duration: "24m",
            order: 4,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_001_004_001",
                type: "video",
                title: "Volumes and Networks",
                url: "https://example.com/video72",
                duration: "20m",
              },
              {
                id: "material_005_001_004_002",
                type: "code",
                title: "Network Examples",
                url: "https://example.com/code22",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_005_002",
        title: "CI/CD Pipelines",
        description: "Automate your deployment workflow",
        order: 2,
        lessons: [
          {
            id: "lesson_005_002_001",
            title: "GitHub Actions Basics",
            description: "Set up automated workflows",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_002_001_001",
                type: "video",
                title: "GitHub Actions Tutorial",
                url: "https://example.com/video38",
                duration: "24m",
              },
              {
                id: "material_005_002_001_002",
                type: "code",
                title: "Workflow Templates",
                url: "https://example.com/code12",
              },
            ],
          },
          {
            id: "lesson_005_002_002",
            title: "Testing in CI/CD",
            description: "Automated testing pipelines",
            duration: "35m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_002_002_001",
                type: "video",
                title: "CI Testing Strategies",
                url: "https://example.com/video39",
                duration: "28m",
              },
              {
                id: "material_005_002_002_002",
                type: "exercise",
                title: "Build Pipeline",
                url: "https://example.com/exercise14",
              },
            ],
          },
          {
            id: "lesson_005_002_003",
            title: "Production Deployments",
            description: "Deploy to cloud platforms with confidence",
            duration: "42m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_005_002_003_001",
                type: "video",
                title: "Deployment Strategies",
                url: "https://example.com/video73",
                duration: "36m",
              },
              {
                id: "material_005_002_003_002",
                type: "document",
                title: "Deployment Checklist",
                url: "https://example.com/doc18",
              },
              {
                id: "material_005_002_003_003",
                type: "quiz",
                title: "DevOps Final Quiz",
                url: "https://example.com/quiz17",
                questionsCount: 18,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_006",
    title: "SQL & Database Design",
    subtitle:
      "Master Postgres, indexing, schema design, and real production patterns",
    description:
      "A complete guide to relational databases, Postgres, optimization, and schema architecture.",
    instructor: {
      name: "Nadia Hassan",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    },
    thumbnail: "https://images.unsplash.com/photo-1559526324-593bc073d938",
    duration: "6h 05m",
    difficulty: "Intermediate",
    categories: ["Databases", "SQL", "Backend"],
    level: 2,
    studentsEnrolled: 1890,
    rating: 4.7,
    tags: ["sql", "postgres", "schema"],
    updatedAt: "2025-09-15T12:00:00Z",
    isFree: false,
    price: { amount: 54.0, currency: "USD" },
    progress: 80,
    chapters: [
      {
        id: "chapter_006_001",
        title: "SQL Fundamentals",
        description: "Master SQL queries and data manipulation",
        order: 1,
        lessons: [
          {
            id: "lesson_006_001_001",
            title: "SELECT Queries and Filtering",
            description: "Writing efficient SELECT statements",
            duration: "25m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_001_001",
                type: "video",
                title: "SQL Basics",
                url: "https://example.com/video42",
                duration: "20m",
              },
              {
                id: "material_006_001_001_002",
                type: "exercise",
                title: "Query Practice",
                url: "https://example.com/exercise15",
              },
            ],
          },
          {
            id: "lesson_006_001_002",
            title: "JOINs and Relationships",
            description: "Combining data from multiple tables",
            duration: "30m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_002_001",
                type: "video",
                title: "Understanding JOINs",
                url: "https://example.com/video43",
                duration: "24m",
              },
              {
                id: "material_006_001_002_002",
                type: "code",
                title: "JOIN Examples",
                url: "https://example.com/code13",
              },
            ],
          },
          {
            id: "lesson_006_001_003",
            title: "Aggregations and GROUP BY",
            description: "Analyzing data with aggregate functions",
            duration: "28m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_003_001",
                type: "video",
                title: "Aggregation Functions",
                url: "https://example.com/video44",
                duration: "22m",
              },
              {
                id: "material_006_001_003_002",
                type: "quiz",
                title: "SQL Basics Quiz",
                url: "https://example.com/quiz9",
                questionsCount: 10,
              },
            ],
          },
          {
            id: "lesson_006_001_004",
            title: "Subqueries and CTEs",
            description: "Advanced query techniques",
            duration: "34m",
            order: 4,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_001_004_001",
                type: "video",
                title: "Complex Queries",
                url: "https://example.com/video74",
                duration: "28m",
              },
              {
                id: "material_006_001_004_002",
                type: "exercise",
                title: "Advanced Query Practice",
                url: "https://example.com/exercise26",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_006_002",
        title: "Database Design",
        description: "Schema design and normalization",
        order: 2,
        lessons: [
          {
            id: "lesson_006_002_001",
            title: "Normalization Principles",
            description: "Design normalized database schemas",
            duration: "32m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_002_001_001",
                type: "video",
                title: "Database Normalization",
                url: "https://example.com/video45",
                duration: "26m",
              },
              {
                id: "material_006_002_001_002",
                type: "document",
                title: "Normal Forms Guide",
                url: "https://example.com/doc12",
              },
            ],
          },
          {
            id: "lesson_006_002_002",
            title: "Indexes and Performance",
            description: "Optimize queries with proper indexing",
            duration: "35m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_002_002_001",
                type: "video",
                title: "Index Optimization",
                url: "https://example.com/video46",
                duration: "28m",
              },
              {
                id: "material_006_002_002_002",
                type: "exercise",
                title: "Index Practice",
                url: "https://example.com/exercise16",
              },
            ],
          },
          {
            id: "lesson_006_002_003",
            title: "Views and Stored Procedures",
            description: "Encapsulate complex logic",
            duration: "29m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_006_002_003_001",
                type: "video",
                title: "Views and Procedures",
                url: "https://example.com/video75",
                duration: "24m",
              },
              {
                id: "material_006_002_003_002",
                type: "code",
                title: "Procedure Examples",
                url: "https://example.com/code23",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_006_003",
        title: "Advanced PostgreSQL",
        description: "PostgreSQL-specific features",
        order: 3,
        lessons: [
          {
            id: "lesson_006_003_001",
            title: "Advanced Data Types",
            description: "JSON, arrays, and custom types",
            duration: "30m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_003_001_001",
                type: "video",
                title: "Postgres Data Types",
                url: "https://example.com/video47",
                duration: "24m",
              },
              {
                id: "material_006_003_001_002",
                type: "code",
                title: "Type Examples",
                url: "https://example.com/code14",
              },
            ],
          },
          {
            id: "lesson_006_003_002",
            title: "Transactions and Concurrency",
            description: "Managing concurrent database access",
            duration: "38m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_003_002_001",
                type: "video",
                title: "Transaction Management",
                url: "https://example.com/video48",
                duration: "32m",
              },
              {
                id: "material_006_003_002_002",
                type: "quiz",
                title: "Advanced PostgreSQL Quiz",
                url: "https://example.com/quiz10",
                questionsCount: 12,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_006_004",
        title: "Production Database Management",
        description: "Manage databases at scale",
        order: 4,
        lessons: [
          {
            id: "lesson_006_004_001",
            title: "Backup and Recovery",
            description: "Protect your data",
            duration: "27m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_004_001_001",
                type: "video",
                title: "Backup Strategies",
                url: "https://example.com/video76",
                duration: "22m",
              },
              {
                id: "material_006_004_001_002",
                type: "document",
                title: "Recovery Procedures",
                url: "https://example.com/doc19",
              },
            ],
          },
          {
            id: "lesson_006_004_002",
            title: "Monitoring and Maintenance",
            description: "Keep your database healthy",
            duration: "31m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_004_002_001",
                type: "video",
                title: "Database Monitoring",
                url: "https://example.com/video77",
                duration: "26m",
              },
              {
                id: "material_006_004_002_002",
                type: "exercise",
                title: "Maintenance Tasks",
                url: "https://example.com/exercise27",
              },
            ],
          },
          {
            id: "lesson_006_004_003",
            title: "Scaling Strategies",
            description: "Scale your database for growth",
            duration: "36m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_006_004_003_001",
                type: "video",
                title: "Database Scaling",
                url: "https://example.com/video78",
                duration: "30m",
              },
              {
                id: "material_006_004_003_002",
                type: "quiz",
                title: "Final Database Quiz",
                url: "https://example.com/quiz18",
                questionsCount: 15,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_007",
    title: "Python for Data Analysis",
    subtitle:
      "Analyze datasets, visualize results, and build predictive insights",
    description:
      "Hands-on training using pandas, NumPy, Matplotlib, and practical data-cleaning workflows.",
    instructor: {
      name: "David Park",
      avatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91",
    },
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c",
    duration: "7h 15m",
    difficulty: "Intermediate",
    categories: ["Data Science", "Python"],
    level: 2,
    studentsEnrolled: 5200,
    rating: 4.9,
    tags: ["python", "data", "analysis", "pandas"],
    updatedAt: "2025-11-01T12:00:00Z",
    isFree: false,
    price: { amount: 79.0, currency: "USD" },
    progress: 50,
    chapters: [
      {
        id: "chapter_007_001",
        title: "Python and Pandas Basics",
        description: "Get started with data analysis in Python",
        order: 1,
        lessons: [
          {
            id: "lesson_007_001_001",
            title: "NumPy Fundamentals",
            description: "Working with arrays and numerical data",
            duration: "30m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_001_001",
                type: "video",
                title: "NumPy Introduction",
                url: "https://example.com/video49",
                duration: "24m",
              },
              {
                id: "material_007_001_001_002",
                type: "code",
                title: "NumPy Examples",
                url: "https://example.com/code15",
              },
            ],
          },
          {
            id: "lesson_007_001_002",
            title: "Pandas DataFrames",
            description: "Data manipulation with Pandas",
            duration: "35m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_002_001",
                type: "video",
                title: "Pandas Basics",
                url: "https://example.com/video50",
                duration: "28m",
              },
              {
                id: "material_007_001_002_002",
                type: "exercise",
                title: "DataFrame Practice",
                url: "https://example.com/exercise17",
              },
            ],
          },
          {
            id: "lesson_007_001_003",
            title: "Data Cleaning Techniques",
            description: "Handle missing data and outliers",
            duration: "32m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_003_001",
                type: "video",
                title: "Data Cleaning",
                url: "https://example.com/video51",
                duration: "26m",
              },
              {
                id: "material_007_001_003_002",
                type: "document",
                title: "Cleaning Best Practices",
                url: "https://example.com/doc13",
              },
            ],
          },
          {
            id: "lesson_007_001_004",
            title: "Data Transformation",
            description: "Reshape and pivot data",
            duration: "29m",
            order: 4,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_001_004_001",
                type: "video",
                title: "Transform Data",
                url: "https://example.com/video79",
                duration: "24m",
              },
              {
                id: "material_007_001_004_002",
                type: "exercise",
                title: "Transformation Practice",
                url: "https://example.com/exercise28",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_007_002",
        title: "Data Visualization",
        description: "Create compelling visualizations",
        order: 2,
        lessons: [
          {
            id: "lesson_007_002_001",
            title: "Matplotlib Fundamentals",
            description: "Basic plotting with Matplotlib",
            duration: "28m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_007_002_001_001",
                type: "video",
                title: "Matplotlib Guide",
                url: "https://example.com/video52",
                duration: "22m",
              },
              {
                id: "material_007_002_001_002",
                type: "code",
                title: "Plot Examples",
                url: "https://example.com/code16",
              },
            ],
          },
          {
            id: "lesson_007_002_002",
            title: "Seaborn for Statistical Plots",
            description: "Advanced visualization with Seaborn",
            duration: "32m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_002_002_001",
                type: "video",
                title: "Seaborn Tutorial",
                url: "https://example.com/video53",
                duration: "26m",
              },
              {
                id: "material_007_002_002_002",
                type: "exercise",
                title: "Visualization Project",
                url: "https://example.com/exercise18",
              },
            ],
          },
          {
            id: "lesson_007_002_003",
            title: "Interactive Visualizations",
            description: "Create interactive plots with Plotly",
            duration: "27m",
            order: 3,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_002_003_001",
                type: "video",
                title: "Plotly Tutorial",
                url: "https://example.com/video80",
                duration: "22m",
              },
              {
                id: "material_007_002_003_002",
                type: "code",
                title: "Interactive Examples",
                url: "https://example.com/code24",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_007_003",
        title: "Real-World Projects",
        description: "Apply your skills to real datasets",
        order: 3,
        lessons: [
          {
            id: "lesson_007_003_001",
            title: "Exploratory Data Analysis Project",
            description: "Analyze a complete dataset",
            duration: "50m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_003_001_001",
                type: "video",
                title: "EDA Walkthrough",
                url: "https://example.com/video56",
                duration: "42m",
              },
              {
                id: "material_007_003_001_002",
                type: "exercise",
                title: "Complete Analysis",
                url: "https://example.com/exercise19",
              },
            ],
          },
          {
            id: "lesson_007_003_002",
            title: "Predictive Modeling Basics",
            description: "Build your first predictive model",
            duration: "45m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_007_003_002_001",
                type: "video",
                title: "Modeling Introduction",
                url: "https://example.com/video57",
                duration: "38m",
              },
              {
                id: "material_007_003_002_002",
                type: "quiz",
                title: "Final Assessment",
                url: "https://example.com/quiz12",
                questionsCount: 18,
              },
            ],
          },
        ],
      },
    ],
  },

  {
    id: "course_008",
    title: "Startup Branding & Marketing",
    subtitle: "Build a brand identity that actually sells",
    description:
      "Learn positioning, brand design, content strategy, storytelling, and the modern marketing stack.",
    instructor: {
      name: "Laura Smith",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    },
    thumbnail: "https://images.unsplash.com/photo-1492724441997-5dc865305da7",
    duration: "2h 50m",
    difficulty: "Beginner",
    categories: ["Marketing", "Branding"],
    level: 1,
    studentsEnrolled: 3100,
    rating: 4.5,
    tags: ["branding", "marketing", "storytelling"],
    updatedAt: "2025-08-10T12:00:00Z",
    isFree: true,
    price: null,
    progress: 90,
    chapters: [
      {
        id: "chapter_008_001",
        title: "Brand Foundations",
        description: "Build a strong brand identity",
        order: 1,
        lessons: [
          {
            id: "lesson_008_001_001",
            title: "Finding Your Brand Position",
            description: "Define your unique market position",
            duration: "22m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_001_001",
                type: "video",
                title: "Brand Positioning",
                url: "https://example.com/video58",
                duration: "18m",
              },
              {
                id: "material_008_001_001_002",
                type: "document",
                title: "Positioning Worksheet",
                url: "https://example.com/doc15",
              },
            ],
          },
          {
            id: "lesson_008_001_002",
            title: "Crafting Your Brand Story",
            description: "Storytelling for startups",
            duration: "20m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_002_001",
                type: "video",
                title: "Brand Storytelling",
                url: "https://example.com/video59",
                duration: "16m",
              },
              {
                id: "material_008_001_002_002",
                type: "exercise",
                title: "Story Framework",
                url: "https://example.com/exercise20",
              },
            ],
          },
          {
            id: "lesson_008_001_003",
            title: "Visual Identity Design",
            description: "Create a memorable visual brand",
            duration: "25m",
            order: 3,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_003_001",
                type: "video",
                title: "Design Fundamentals",
                url: "https://example.com/video60",
                duration: "20m",
              },
              {
                id: "material_008_001_003_002",
                type: "document",
                title: "Design Guidelines",
                url: "https://example.com/doc16",
              },
            ],
          },
          {
            id: "lesson_008_001_004",
            title: "Brand Voice and Messaging",
            description: "Develop your unique brand voice",
            duration: "21m",
            order: 4,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_001_004_001",
                type: "video",
                title: "Voice and Tone",
                url: "https://example.com/video81",
                duration: "16m",
              },
              {
                id: "material_008_001_004_002",
                type: "exercise",
                title: "Voice Workshop",
                url: "https://example.com/exercise29",
              },
            ],
          },
        ],
      },
      {
        id: "chapter_008_002",
        title: "Content Strategy",
        description: "Create content that converts",
        order: 2,
        lessons: [
          {
            id: "lesson_008_002_001",
            title: "Content Marketing Fundamentals",
            description: "Build a content strategy",
            duration: "24m",
            order: 1,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_002_001_001",
                type: "video",
                title: "Content Strategy",
                url: "https://example.com/video61",
                duration: "20m",
              },
              {
                id: "material_008_002_001_002",
                type: "exercise",
                title: "Content Calendar",
                url: "https://example.com/exercise21",
              },
            ],
          },
          {
            id: "lesson_008_002_002",
            title: "Social Media Marketing",
            description: "Grow your audience on social platforms",
            duration: "26m",
            order: 2,
            isCompleted: true,
            learningMaterials: [
              {
                id: "material_008_002_002_001",
                type: "video",
                title: "Social Media Guide",
                url: "https://example.com/video62",
                duration: "22m",
              },
              {
                id: "material_008_002_002_002",
                type: "quiz",
                title: "Marketing Quiz",
                url: "https://example.com/quiz13",
                questionsCount: 8,
              },
            ],
          },
        ],
      },
      {
        id: "chapter_008_003",
        title: "Growth and Analytics",
        description: "Measure and optimize your marketing",
        order: 3,
        lessons: [
          {
            id: "lesson_008_003_001",
            title: "Marketing Analytics",
            description: "Track and measure marketing performance",
            duration: "20m",
            order: 1,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_008_003_001_001",
                type: "video",
                title: "Analytics Basics",
                url: "https://example.com/video63",
                duration: "16m",
              },
              {
                id: "material_008_003_001_002",
                type: "document",
                title: "Metrics Guide",
                url: "https://example.com/doc17",
              },
            ],
          },
          {
            id: "lesson_008_003_002",
            title: "Growth Hacking Strategies",
            description: "Scale your startup marketing",
            duration: "22m",
            order: 2,
            isCompleted: false,
            learningMaterials: [
              {
                id: "material_008_003_002_001",
                type: "video",
                title: "Growth Tactics",
                url: "https://example.com/video64",
                duration: "18m",
              },
              {
                id: "material_008_003_002_002",
                type: "quiz",
                title: "Final Marketing Quiz",
                url: "https://example.com/quiz14",
                questionsCount: 10,
              },
            ],
          },
        ],
      },
    ],
  },
];
